### ISSUE TITLE
Any chance porting this to Userstyles?

### ISSUE THREAD

**Issue by bzx** [leggett/simplify#11]
...because it would be possible to use it in all browsers using Tampermonkey extension.

**Comment by leggett** [comment]
No. I want to make sure that the custom style doesn't mean users have to give up anything on privacy or data security and I have concerns about Userstyles' new owner, SimilarWeb.

**Comment by Mrfiregem** [comment]
Not uploading it to the site Userstyles is something I understand, as they don't have the best repulation, but making this a userstyle file would be great, since it could then be used in most browsers through extensions like [Stylus](https://github.com/openstyles/stylus/). 

Userstyles are just local CSS files that contain some meta code, similar to userscipts. I think it'd be a great idea to make this a userstyle.

**Comment by leggett** [comment]
We're going to work on porting it to other growers directly.
