### ISSUE TITLE
Can we add a "Mark as read & Archive" button?

### ISSUE THREAD

**Issue by davelavoie** [leggett/simplify#136]
Hi there! 
Thanks for your project, this is really a great extension and I would eventually like to contribute one way or another when I've got time.

I was wondering if we could add a button that would do both "Mark as read" and "Archive" actions at once. I never archive unread emails (every week I'm searching for unread mails in my inbox just to make sure I didn't miss any, this is even more true since Inbox is dead, I keep losing emails since then). So clicking on "Mark as read" first, and then "Archive" makes the process longer for nothing.

The icon could be displayed next to the others when hovering an email item:

![buttons](https://user-images.githubusercontent.com/3408028/57027257-eb517380-6c09-11e9-8f40-033522806f73.png)

I'm aware this might not be the default behavior and I know this isn't necessarily ideal to add a fifth icon... In order to avoid that, the extension could have an option allowing the user to decide what's the behavior of the Archive button (default behavior, or both Mark as read + Archive), or even which icon should be displayed.

Any thoughts?

Thanks!

**Comment by leggett** [comment]
Thanks for the suggestion Dave. It wouldn't be easy, but I could possibly do this if I could get simulating clicks to work. The problem is the undo action wouldn't be for the combined action -- it would only un-archive it. For that reason (and because I've already got too much on my plate), I'm going to decline to do this.
