### ISSUE TITLE
Tab Gradients missing

### ISSUE THREAD

**Issue by sajjaadf** [leggett/simplify#137]
_Supposed to look_
![02](https://user-images.githubusercontent.com/32078755/57046254-bbfc3000-6c24-11e9-9225-63eb70eef73e.png)
**How it looks**
![Screen Shot 2019-05-01 at 3 22 20 PM](https://user-images.githubusercontent.com/32078755/57046315-ed74fb80-6c24-11e9-9d63-7031c606b526.png)

**Comment by leggett** [comment]
Are you talking about the underline under the tab? If so, this is intentional. I removed that in a more recent version (after the early screenshot). 

I didn't think it would make a big difference but I was wrong -- I love the change so much as (1) the difference in opacity and color is enough to highlight the current tab and (2) the lack of a bold horizontal line makes it easier for the eye to scan down from the tab into the first item.

Re-open if you meant something else.

**Comment by sajjaadf** [comment]
is it possible to have a on off toggle?

**Comment by leggett** [comment]
For Simplify as a whole or do you mean for the tab underlines?

**Comment by sajjaadf** [comment]
like a options page to toggle certain features on / off

**Comment by leggett** [comment]
Ah, got it. No, I don't want to add any settings as it greatly increases the difficulty of supporting the extension (as I have to test all the combinations of settings). It is also a cheap way to avoid making hard decisions. And finally, not many people customize things in general so you end up adding a lot of overhead to supporting the extension for the slim minority of people. A few things are sticky (for example, if search is left open, it will stay open). But that's it.

**Comment by sajjaadf** [comment]
is it possible to modify the extension?
[image: Picture]
Sajjaad Farzad
*About Me <http://sajjaadf.github.io/>*
