### ISSUE TITLE
Add an option to toggle a light icon on for dark themes

### ISSUE THREAD

**Issue by maxwelljordanwhite** [leggett/simplify#146]
With Chrome's new Dark Mode the icon is nearly invisible

**Comment by leggett** [comment]
Made the icon gray so it stands out on light and dark browser themes.

**Comment by lydenyardley** [comment]
This is still not fixed for me in 1.5.3:
![Screenshot 2019-06-03 at 21 31 17](https://user-images.githubusercontent.com/2838799/58832501-f9e6dc80-8646-11e9-9478-b58732a543dc.png)

**Comment by leggett** [comment]
Bummer. It is fixed in the official dark theme:
<img width="225" alt="Screen Shot 2019-06-03 at 1 37 58 PM" src="https://user-images.githubusercontent.com/8763662/58833017-04808200-8605-11e9-88b2-eb45172a0a95.png">

... but in dark-gray themes, I guess not. It is rough because as far as I can tell, there isn't a way to find out what the browser theme is. Here is a recent discussion on the 1Password forum: 
https://discussions.agilebits.com/discussion/102302/extension-icon-in-chrome-dark-mode

So the icon needs to just work in all instances (which means putting a background on it or making it a bright color so it pops on all backgrounds which I don't want to do). I'll probably add a light gray background so it isn't visible in the default theme. 

... unless someone has a better idea.

**Comment by lydenyardley** [comment]
This *is* the official dark theme. As in, I haven't set a theme - it just changes at sunset according to my Mac settings!

Side note... Mine looks a lot like yours when the browser isn't viewing Gmail...

**Comment by leggett** [comment]
Good catch -- I see what you see now. I'll add an ugly background or something for now.

**Comment by leggett** [comment]
Ugly background coming in v1.5.9.  🎉
