### ISSUE TITLE
Toolbar overlapping composer

### ISSUE THREAD

**Issue by dzenvikas** [leggett/simplify#164]
When composer is at its max-height, it overlaps with toolbar.
<img width="1440" alt="स्क्रीन शॉट १९४१-०२-२२, पू ११ २५ १५ पर" src="https://user-images.githubusercontent.com/24394958/57578659-0e9fdc80-74ae-11e9-8074-c6cd8c57b6a5.png">

**Comment by leggett** [comment]
It took me a while to recreate this. Writing a long email, I couldn't get the bar to overlap but eventually I found an odd set of conditions that appear to recreate it. And it appears to be a Gmail bug (sort of) that is somehow worse with Simplify on (even though I don't actually do anything to style the composer window).

For me, this happens when I have a long email in the composer, nothing in the To field, I maximize it and then pop it back into a smaller window. Gmail takes me focus when I do this and puts it in the To field which expands the header. But instead of pushing the body down, it pushes the top of the compose window up. Clicking back in the body of the email fixes it for me.

I couldn't recreate the bug any other way and it seems to have an easy fix (put focus back in the body of the email). If it is happening more often for you or under other conditions, please re-open the issue and give some more info. Thanks.

![composer_overlap](https://user-images.githubusercontent.com/8763662/57595630-10dc5800-74fb-11e9-9ee2-b380f1283d2f.gif)
