### ISSUE TITLE
Firefox In-Mail images too large

### ISSUE THREAD

**Issue by nrichards** [leggett/simplify#190]
Email images are sized incorrectly when Simplify Add On is enabled in Firefox.
FFX 67.0 (64-bit) MacOS
Simplify v 1.5.6

I did not investigate WHY, but image sizes are semi-broken in the normal mail preview.

Interesting - the sizes are CORRECT if I hit "Reply" and examine the "..." quoted HTML message.

Demo (HTML + PNG):

[Diablo now with Hellfire • Bethesda joins the Summer Sale Festival.eml.txt](https://github.com/leggett/simplify/files/3259359/Diablo.now.with.Hellfire.Bethesda.joins.the.Summer.Sale.Festival.eml.txt)
![image](https://user-images.githubusercontent.com/704698/58996472-40564b80-87ad-11e9-8057-07b71d74bb66.png)

**Comment by nrichards** [comment]
And thanks again for the killer Extension.

**Comment by leggett** [comment]
Interesting... first off, thanks for the excellent documentation. 

The two things I'm doing that contribute to (but don't fully explain) what is going on here:

1. I set a max-width on the conversation. But content can force that to be wider -- for some reason, this email isn't forcing it to be wider and letting you scroll horizontally.
2. I set images to a max-width of the content (usually 960px or 1100px) so really really big inlined images don't force all the content to stretch super wide. I don't think this is having an impact here. 

So I think something weird is going on mostly b/c of the template used in the html email isn't designed to work at 960px. I'd say that is just a bad template. It isn't a probably with Simplify off because Gmail lets the conversation be the full width of the screen (which is a horrible experience for 99% of emails that you actually want to read).

If you want me to trouble shoot further, forward the email to hi.simplify@gmail.com and if I find an issue with Simplify, I'll re-open the issue.
