### ISSUE TITLE
GitHub newsletter showing large fork icon

### ISSUE THREAD

**Issue by cassiobock** [leggett/simplify#196]
Hi,

The fork icon on the GitHub newsletter is getting really big when the extension is active. I'm using Firefox 67.0.3

On
![image](https://user-images.githubusercontent.com/3936166/59923694-6c5b0900-940a-11e9-89df-2069eaf619f4.png)

Off
![image](https://user-images.githubusercontent.com/3936166/59923775-9a404d80-940a-11e9-96a2-bc2940e53361.png)

**Comment by leggett** [comment]
Can you forward the email to hi.simplify@gmail.com and I'll make sure my latest change fixes this?

**Comment by cassiobock** [comment]
@leggett Sure, I've sent you the email a few minutes ago.

**Comment by leggett** [comment]
Thanks for forwarding it. I've diagnosed the issue and come up with an ok but not great fix. 

**Context:**
1. Large inline images cause horizontal scrolling (plus you can't see the whole image)
2. The best practice to address this is adding `max-width:100%; height:auto;`
3. Without the `height:auto` large portrait images will keep their original height while shrinking the width which will make the image look squished.
4. But, with the `height:auto` large images that have been shrunk down but not given a height in the correct way, will actually get enlarged to their natural size. 

**What is happening here** 
GitHub email uses a [large 180x180 image](https://github.githubassets.com/images/email/explore/octicon-fork.png) for the 14x14 fork icon AND they set the height of the image with a height attribute instead of css (e.g., `<img height="14">`). My `height:auto` is pushing the icon up to its natural 180x180 size.

**Options:**
1. Let large inline images be large and scroll the page horizontally. This is what Gmail does and I'd really like to not do this because it sucks. That said, messing with the style for html emails is super risky & unpredictable... it is like applying css to the entire web. It is going to break something. So I wouldn't be surprised if I end up falling back to this some day.
2. I could remove the `height:auto` and just let large inline portrait images be squished. That sucks for obvious reasons.
3. I could just let images that don't have their height set appropriately (as GitHub did here) be broken. I'd say this is better than option 2 but still not ideal.
4. What I ended up doing was adding css that fixes GitHub's mistake. I set the height in css based on height html attribute. `html.simpl table.Bs .gs img[height="14"] { height: 14px; }` and I added that for every size between 0px and 100px. Hopefully this is only a problem with icons or small profile photos. 

If anyone has a better idea for how to solve this, let me know please.

I'll publish this fix as part of v1.5.9.
