### ISSUE TITLE
Can we override or disable the garbage hotkeys in lieu of replacing them with the far better ones from Inbox?

### ISSUE THREAD

**Issue by Leopere** [leggett/simplify#200]
Ever since inbox.google.com has been axed I find it nearly impossible to keep up with the workflow that I used to plow through via Inbox in a matter of minutes using keyboard shortcuts. 

What used to be simple `[` `]` `j` `k` `e` etc... is now just a total fucking kludge of bs.  I want to be able to skip the whole multi-select required by default with these god awful checkboxes and junk in my Gmail interface and have the ability to rapidly plow through my email again.  Please give me this back your wonderful team of human beings.  OR just make a super awesome Inbox.Google.Com replacement client that can be self-hosted, that would be the absolute finest thing a human could do.

**Comment by leggett** [comment]
1. Gmail has many of the same keyboard shortcuts. You see them all  and enable them if they aren't already via the [ ? ] key.

2. You can customize the shortcuts via Gmail's advanced feature, Custom Keyboard Shortcuts. It is under Gmail Settings > Advanced > Custom keyboard shortcuts

3. If the above two don't work, I can override or add shortcuts myself via Simplify. I've added two already though I haven't advertised them a ton because I'm not happy with the shortcuts I've chosen so far. To consider this, can you describe your exact workflow in more detail and explain how Gmail falls short?

**Comment by Leopere** [comment]
I guess my issue is that I got so used to precisely the keys that Inbox had.  I'm not exactly stuck on it and after filing this issue I did come across what you mentioned in point number 2 there.

I got as close as I could from screenshots I found online.  My main complaints further still is the fact that it seems impossible to just use J/K to switch between conversations and then press a single key to set a reminder, archive, delete, report as spam.  I have to instead select an email open the thing and then I can do those other hotkeys OR I use X to select the mail that might have a similar next action like labels or whatever and then it can be archived or whatever with a secondary hotkey.

In Inbox this was a single hotkey.

However, as much as I love the idea of continually leaning on Google for things if you're going this far would it not be just as if not more awesome to just make a nice client that people don't have to lean on others for?  There are too many ways these days to host things for yourself however it seems that nobody is coming up with a forward-thinking UX for things like Email.  It all just tries to be exactly as it was.  Inbox kind of really blew that whole mentality out of the water which was really quite a nice thing.

I'd love to get away from gmail entirely.

**Comment by leggett** [comment]
Got it -- your request to not have to select a message to use a keyboard shortcut is something on my radar (see issues #78). So I'll close this ticket as the other one should cover your request. 

FWIW, I think the best workflow (and this mimics Inbox's flow somewhat well) is to stay in conversation view and use the bracket keys `[` and `]` to archive and go to the next message. Just start at the top and plow through it. The original design for Inbox actually had all messages opened so marking done or even just scrolling defaulted to seeing the next message. It was polarizing... some loved it (myself included) and some didn't. There is a lot of time wasted trying to choose the right next message to open and it is made worse when we use things like "Mark as unread" to flag the items we want to come back to. 

As for the idea of building my own email client... I don't disagree that there is a lot more that could be done to build something really innovative. And I think I could lead that. So, maybe someday. But that is a much much much bigger endeavor than what I'm doing with Simplify (which is just a side project for me). My main job is running product for a company working on climate change and that feels much more important to me than more innovative email. 

More likely, I will write about what I think an innovative email client should be so that anyone can execute on them.

**Comment by Leopere** [comment]
Well, thank you very much for your time on this matter it makes life
much easier and I gotta say that I'm very interested in doing whatever I
can to enable you to spend any time on the Email client especially if its a
self hostable web app because I'm just super into that.

Especially if we can nudge it towards having GPG made trivial somehow it
would just be a glorious day and win for the world.
