### ISSUE TITLE
Throw error when user has multiple inboxes AND preview pane enabled (as they are not compatible)

### ISSUE THREAD

**Issue by noamross** [leggett/simplify#211]
I have two Gmail accounts typically open in two different accounts.  For both I keep message preview on. For my personal account, Simplify limits the width of the list of messages and the message preview, together to a max width. For my business (Google Apps) account, Simplify instead limits the content of the email width to a maximum value.   I think the latter is the correct behavior (at least it's how I prefer it).  Any idea what causes the difference.  Happy to provide info from the Inspector if relevant.

Here are screen shots.

*Personal Account* 
<img width="1908" alt="Screenshot 2019-08-06 14 58 54" src="https://user-images.githubusercontent.com/571752/62568617-a027ac00-b85b-11e9-9343-6df4870a98f3.png">

*Apps Account* 
<img width="1901" alt="Screenshot 2019-08-06 14 59 12" src="https://user-images.githubusercontent.com/571752/62568627-a453c980-b85b-11e9-8e00-ab64cf6d6c07.png">

**Comment by leggett** [comment]
Thanks for the detailed report with screenshots. What you see in your personal account is a bug for sure. It is never supposed to do that. Preview pane should always take up the full window and only limit the width of the content itself. 

I've seen this on occasion but I haven't been able to figure out how or why this happens but I've found that often refreshing Gmail or restarting Chrome fixes it (which makes it all that much more confusing).

**Comment by leggett** [comment]
If that doesn't fix it, let me know and I'll let you know if you can help troubleshoot.

**Comment by noamross** [comment]
The behavior on the personal account persisted after refresh, quit-and-restart, and cache-clear-and-hard-refresh.  So I dove into my settings to see if there was anything different between the accounts, and found I had "Multiple Inboxes" turned on in "Advanced" on the personal account.  I turned this off, refresh, and turned the extension off and on, and that fixed it. 

Turning Multiple Inboxes back on reverted to the buggy behavior.  I note with Multiple Inboxes on the main inbox element is `<div class="nH bkK nn" style="width: 2492.53px;">`, with it off that element is `<div class="aia" gh="tl">`.

**Comment by leggett** [comment]
Nice sleuthing! Did you only have one section in Multiple Inboxes? I didn't see inbox sections in either screenshot... just preview pane. I'll look at it some more now that I know what to look at.

**Comment by noamross** [comment]
Yes, I only had one section in multiple inboxes. I guess I had the feature from when I tried it out on but don't use it.

**Comment by leggett** [comment]
The problem is preview pane is not compatible with multiple inboxes. What I didn't account for is you can enable multiple inboxes and specify no additional inboxes and it looks like multiple inboxes is off but it isn't fully and it messes things up. The thing I use to detect multiple inboxes (the "view all" button): `document.querySelectorAll('div[role="main"] span[action="viewAll"]').length;`

This "view all" button is only present if you have at least one separate inbox specified in multiple inboxes... so I've got to find a way to detect multiple inboxes even if no additional inboxes are specified. And then I need to show a warning if both that and Preview Pane is enabled. 

`<div class="aia" gh="tl">` exists with multiple inboxes on or off. My current thought is that the action bar is moved inside the main div when multiple inboxes is enabled: `document.querySelectorAll('div[role="main"] div[gh="tm"]').length`

But it is also moved like this for Preview Pane. And while I can detect if Preview Pane is enabled by checking for the existence of the view toggle: `document.querySelector('div[selector="nosplit"]')` this still doesn't tell me if _both_ are enabled at the same time with Multiple Inboxes not having any inboxes setup. So more work to do... but I'm now aware of an edge case I hadn't accounted for thanks to your help. So thank you!

**Comment by leggett** [comment]
Gmail doesn't let you get into this state any more.
