### ISSUE TITLE
Make refresh button always visible in Reading Pane view

### ISSUE THREAD

**Issue by GorvGoyl** [leggett/simplify#269]
Refresh button is visible when I first reload the gmail page. but when I select any mail it gets hidden. Why? It should be visible all the time so that user can use it to check for new mails.

**Comment by ahatzz11** [comment]
Are you referring to this refresh button? (on the left)
 
![image](https://user-images.githubusercontent.com/6256032/80541289-8477af00-8970-11ea-8925-b9a053aa8475.png)

If so - this is actually the symbol used when downloading mail for offline use. Gmail should show new emails without having to reload.

**Comment by JerryGoyal** [comment]
no, that's a different button as you mentioned. I'm talking about the refresh button on the top left toolbar.

See on the left side:
![image](https://user-images.githubusercontent.com/7106086/80543212-14971200-89cc-11ea-95f7-d695b605b9bd.png)

It is visible only when you reload the gmail and do not click on any mail. Once you open any mail then refresh button is gone.
Like this:

![image](https://user-images.githubusercontent.com/7106086/80543421-78b9d600-89cc-11ea-94df-99509565eb2d.png)


_Gmail should show new emails without having to reload._
--> I know but it takes some seconds to fetch new mails but if I click on refresh it fetches the new mails instantly. One use case is when I get OTP/account verification email, I want to instantly refresh the gmail for that email instead of waiting for gmail server to fetch it after some delay.

**Comment by ahatzz11** [comment]
Oh interesting, I've never really noticed that one before! I was able to click on some mail and go back to my inbox and it's still there. However - I don't have the side-by-side conversation view so that might be a contributor to the issue.

**Comment by JerryGoyal** [comment]
Glad you understood the problem. Would it be possible for you to fix this? Really appreciate that!

**Comment by ahatzz11** [comment]
I didn't plan on doing any contributions yet, was just looking through some of the issues for now! Based on https://github.com/leggett/simplify/issues/70#issuecomment-617201287 it sounds like @leggett has some stuff in the works, so maybe this can make the list!

**Comment by leggett** [comment]
In side-by-side view, the refresh button is hidden by Gmail (not Simplify) when you open an email. So I can't unhide it.

**Comment by leggett** [comment]
I dug into this a little more and they don't remove the button entirely (what I thought they were doing). They just hide it. So I actually _can_ unhide it. I'll reopen this and think about it some. There may be reasons not to do this. 

P.S. Clicking on the label you are on in the nav (e.g., click on the Inbox when you are in the inbox) does the same thing as the refresh button (fetches any new mail without reloading the whole page). This is made a bit harder with Simplify turned on if you hide the nav because I fully hide it from view.

**Comment by JerryGoyal** [comment]
Thank you for reopening the issue. 

>  There may be reasons not to do this.
I have temporarily enabled refresh button by doing some css hacks locally (lasts until I reload) and I didn't find any issue/bug. I've been testing it for few days. 
```
.bzn .G-tF .G-Ni.J-J5-Ji{
	display: inline-flex !important;
}
```

>  Clicking on the label you are on in the nav (e.g., click on the Inbox when you are in the inbox) does the same thing
That's how I was doing before simplify but now simplify hides the navbar 😅.

**Comment by leggett** [comment]
I added this in Simplify v2. Thanks for the original request. You can also use ⌘R or Ctrl+R to refresh the list (it clicks on this button if you're in list view).
