### ISSUE TITLE
Mirror functionality from the new hey.com email service

### ISSUE THREAD

**Issue by cy2k** [leggett/simplify#283]
Have you seen this yet? Wow
https://www.youtube.com/watch?v=UCeYTysLyGI

I might leave Gmail for this...

Any functionality that might be possible to replicate within Gmail, though, would be amazing.
https://hey.com/features/
- finding and blocking tracking pixels
- combining email threads
- putting unread emails into a single scrollable feed where you can read them all one after another with no clicks
- grouping new emails all at the top, and everything else below, in separate sections

I don't know if any of these are remotely possible...  I didn't even bother mentioning the features that seem impossible.

Mostly just wanting to start a conversation about it.  Seems like a really exciting service, trying to fix long standing issues with email.

**Comment by leggett** [comment]
Just saw it yesterday. 

Have lots of thoughts (pretty much all good). This has a lot of the patterns Google Inbox had and some we had in early versions but sadly, never launched (like feed view / read together).

Of what I've seen so far, things fall into one of 5 buckets:
1. Already possible in Gmail (like unread on top)
2. Will be in Simplify v2 (like blocking email trackers)
3. Could be in Simplify v2 but I don't want to (because I disagree it is better or don't want to do it if it isn't mirrored in Gmail on mobile)
4. Could be in a future version of Simplify if I decided to ask users for full API access (something I've wanted to avoid).
5. Can only be added by Gmail itself (like feed view)

I'll detail what falls into what bucket in my newsletter in the coming weeks: on.simpl.fyi

**Comment by leggett** [comment]
Finally closing out this issue. Some things like blocking email trackers launched with Simplify v2. I think I actually block more trackers (175) than Hey.com (50).

If you love grouping unread emails, I highly recommend Priority Inbox with Unread, Starred, Drafts or Sent, Everything else. I wrote more about how I [use this setup to regularly get to Inbox Zero](https://twitter.com/leggett/status/1363941342968041472).

I'm not sure what the future holds, but if the subscriptions launch goes well, I'd love to start exploring how much more I could do / change with full API access. It will always be optional (I want Simplify to still be great with minimal access) but I'd love to take a swing at things like feed view.
