### ISSUE TITLE
📌 v2 Feature Request: Pin Email to Top

### ISSUE THREAD

**Issue by surjithctly** [leggett/simplify#287]
I would love to see an option for pinning an email to the top. There are certain time, we wanted to remember about an email until a  specific time, or an email we check multiple times for its content. 

Example Use Case: A client send a requirement of a project needs to be done and put all of his ideas/content/screenshots in the email. The project took around 1 month. By the time, our email would fall below which make it difficult to find each time. 

I guess to make this, you need to 1) Move the `<tr>` to the top using JS and then style using CSS. Also clicking on checkbox would show an additional action to pin / unpin that email.

Your thoughts?

~Surjith

**Comment by leggett** [comment]
Unless I require full API access to your email (something I'm trying to avoid), I won't be able to keep it pinned as soon as it is not in your first 100 emails. So this is the kind of feature I am hesitant about. 

**I also think you can already do this with Gmail.**
You can get something like this with one of the inbox setups. For example, opt for Multiple Inboxes with is:starred as the first section. If you don't want all starred items, you can enable multiple stars in General Settings and then search for just that kind of star. You can get the search term by hovering over it (adding the red exclamation mark => search for `has:red-bang`)

**I do plan to offer a way to toggle to see only starred emails.** 
This will still only show you the starred emails in the current view, but (a) it is something Google Inbox had and maybe Gmail would bring it back some day and (b) it has the side benefit of being a focused view where you're also not distracted by any other email including new mail.

I'm going to close this ticket since I don't plan to build exactly what you are suggesting but feel free to add a comment with any additional thoughts or feedback.

**Comment by surjithctly** [comment]
I like the idea of using stars & multiple inbox, however the problem is when activating multiple inbox, The default Tabbed view won't be available.

**Comment by leggett** [comment]
Correct, that is a downside of that path.
