### ISSUE TITLE
Whitespace width threshold too high (for me!) 

### ISSUE THREAD

**Issue by wlonkly** [leggett/simplify#288]
(I saw #250 but I think this is a different issue.)

I just installed Simplify for the first time, and was surprised that I didn't get all that nice calming whitespace on either side of my message list, even with preview disabled. I poked at things a bit, and noticed that if I widen my browser window _slightly_, I get the whitespace. (The reason my browser is not the full width of my MBP display is that I use Sidewise to give me side tabs, like so:)

<img width="512" alt="Screen Shot 2020-07-01 at 11 46 50 PM" src="https://user-images.githubusercontent.com/1545955/86314514-ea451900-bbf5-11ea-808d-d9ab122b4084.png">

I see the whitespace toggles on/off at 1278px:
 https://github.com/leggett/simplify/blob/a0db33210f6cf41be9f7066a4ca514a3e9455fd2/gmail/style.css#L552

so I suppose I am here to suggest that it is too wide a threshold.

It looks like that threshold was updated in #213 to detect narrower popout windows, but was formerly 1200px. I know it's arbitrary, but a lot of the minimalist value of Simplify come that white space, and so I'd love it to be arbitrarily somewhat smaller than 1278px please? :) 

(The threshold that would work for me is probably around 1240. I have no idea how to figure out the "best" threshold, though.)

The width behavior might also be a good thing to mention in the "it's not working for me" FAQ.

Thanks for making Simplify!

**Comment by leggett** [comment]
Thanks for the feedback. I agree it isn't ideal as it is. 

But, it works better in Simplify v2. I shrink the width of the list around 1350px from 1100px wide to 960px wide so there continues to be whitespace on either side of the list. I also now show the nav when you hover over the menu button making it even easier to keep it minimized. And I'm applying a narrower max-width to the conversation than I do to the list so conversation view looks even better. 

I'm trying to finish v2 as fast as I can to deliver all the awesomeness instead of trying to back-port it to v1. So stay tuned!

**Comment by wlonkly** [comment]
Sounds good, I can satisfy my needs with a fork in the meantime. Looking forward to v2!
