### ISSUE TITLE
New G Suite Integrations

### ISSUE THREAD

**Issue by dphall1** [leggett/simplify#297]
I'm curious how you thinking about approaching the upcoming G Suite integrations that were recently announced. I've enjoyed utilizing the Simplify extension since it was released because it combines a much-improved design while keeping the core functionalities of Gmail. Will the new integrations (Meet, Chat, etc.) be navigatable while maintaining the Simplify design principles?

**Comment by leggett** [comment]
Yes, any new features will be supported.

My aim is to never block you from using any feature. There are a few things that Simplify v1 blocks / hides entirely (like the help button) that I am working to make accessible in Simplify v2. 

The two main challenges in supporting larger changes like this are

1. Access to the changes so I can support them (I don't get early access to anything and I can't figure out how to support it until I can see how Gmail's code changed because of the change). This is even harder when it is rolled out for paid G Suite and not consumer accounts as I do not have a paid G Suite account.

2. Managing the time between a feature coming out and Simplify supporting it. If the feature lands, it might be worse than Simplify not supporting it, it might be that some big things break resulting in Gmail + Simplify being a broken experience. I might look into having a way to disable Simplify for all users in Simplify v2 if this happens (kind of an emergency kill switch) until I can support the new changes.

**Comment by dphall1** [comment]
That makes sense. Looking forward to seeing how things develop as Google releases these new integrations. 

Also, I just read the Computerworld article and I'm very excited to see what you do with other applications. Have you ever considered venturing into mobile app development as well? The mobile Gmail app is less cluttered than the web version but I would be interested to see what you might do from a design perspective on mobile. 

Thanks for your work!

**Comment by leggett** [comment]
I can't modify mobile apps the same way I can modify web apps. Chrome doesn't even support extensions in their mobile browser. Firefox does, but way fewer people use Firefox mobile AND even fewer use apps like Gmail in a mobile browser vs the native app.

So any efforts on mobile (none planned right now) would be either be separate apps to supplement workflows that I think should be better supported OR new apps entirely (maybe an Android Launcher or something in the vein of Google's [Android Experiments](https://experiments.withgoogle.com/collection/digitalwellbeing).

**Comment by dphall1** [comment]
That makes sense. If you ever venture down that road (Android launcher) I'll definitely check it out. Looking forward to Simplify v2. Thanks again.
