### ISSUE TITLE
Date headings break when email comes out of snooze

### ISSUE THREAD

**Issue by scottsb** [leggett/simplify#306]
When a snoozed message reappears, it causes the date headings to appear incorrectly. For example, here "This Month" appears before "Yesterday." Additionally there are emails from today in the "This Month" section:

![Screenshot 2020-08-28 11 36 13](https://user-images.githubusercontent.com/6756989/91608107-ec4ffd80-e942-11ea-8755-02ae8e30acae.png)

**Comment by leggett** [comment]
Strange... on a number of levels. 

1. The snoozed message shouldn't have broken up the set of emails to begin with. 
2. And after being opened, I thought it returned to its original time slot (instead of staying put as suggested by your screenshot). 

If you hit refresh, does it stay there? And does "This month" stay above "Yesterday"?

**Comment by scottsb** [comment]
The emails in my inbox have evolved now to the point that the situation no longer applies, so I can't investigate in depth. However, I had refreshed before submitting this, and the same situation had remained without change.

**Comment by leggett** [comment]
Thanks -- I'll try to recreate.

**Comment by pearceshaun** [comment]
I also see this sometimes after snoozed emails return to the inbox. I’m signed up for the V2 beta so will let you know if it happens there during testing.

**Comment by leggett** [comment]
I fixed this a long time ago. Finally closing the issue. Thanks for the original report that raised my awareness.
