### ISSUE TITLE
Feature Request: Persistent display of label list (when reading emails)

### ISSUE THREAD

**Issue by phaseburn** [leggett/simplify#311]
When you open an email, the label list disappears. I know you can get to it by hovering the mouse over the menu icon at the top left, but for somebody who goes through labels and treats them as separate inboxes, etc, it would be a lot more convenient to have the label list (and the unread numbers next to them) displayed all the time while I'm reading emails and performing the work asked of me in them.

I do feel the list being hidden by default is probably better for more people, but an option to allow this for those of us who use labels like that would be appreciated. Can submit screenshot if required to better explain.

**Comment by leggett** [comment]
No screenshot required. 

The two big reasons I hide the nav in conversation view:

1. A more focused reading experience 
2. To make space so I can push the conversation to the left if you have an open compose mole or popped out reply. 

Knowing those benefits, would you still rather keep it open all the time? A few other early beta testers have mentioned this as a pain point so I think it is likely I will at least add an option to keep it visible. But I ask because I want to figure out what the default option should be.

**Comment by ScottESanDiego** [comment]
I agree with @phaseburn . 

On paper I liked the "focus on the message being read" idea and hiding the label list, but in practice for how I read emails it ends up being:
1) Distracting, since the labels are constantly doing hide/show on their own
2) Not conducive to having an email open and seeing if something else arrived (e.g., I'm looking at a message to "follow along" in another window, but want to keep the context of knowing that I just had something important arrive in the Inbox

I think (2) is what @phaseburn was describing.  An option to "Always show labels/tree/whatever-you-call-it" would be good.

**Comment by phaseburn** [comment]
My personal preference is that it should be at minimum an option, potentially the default if more people prefer it. As @ScottESanDiego described, in theory/on paper it _sounds_ good to hide it and focus, but in actual use it's just far more useful to have it displayed all the time for my workflow.

**Comment by baychang** [comment]
The transition is jarring when you open a conversation, and distracts. It's a two-step transition: the message list becomes the conversation and it moves UP and then LEFT. When returning to the message list the two steps are reversed. It might be better with just a single-step transition, but I think it would still be distracting.

**Comment by leggett** [comment]
@baychang bingo. Was waiting for someone to bring this up. I have spent more time than I wish to admit dissecting this transition (including recoding the inspector and playing it back frame by frame) trying to figure out why I can't get it to be a single change. :/

I expected everyone to notice and complain about it. Even if they don't, I find it unacceptable. I suspect those who haven't noticed it still notice it subconsciously damaging the perception of Simplify's solidness.

**Comment by phaseburn** [comment]
While I fully admit that transitions are important, and bad ones can be jarring, I also have to consider the usability of the final outcome post-transition. What really matters more?

1) A usable interface, poorly transitioning into another usable interface. 
2) A usable interface transitioning well into a clunky, and less usable interface.

I find option 2 personally better, as the end result is more acceptable and causes less frustration than a temporary jarring experience that I will forget about shortly after. Ideally fixing both is the perfect solution and my preference, but, you know, if I could only have one or the other...

**Comment by leggett** [comment]
@phaseburn I assume you meant you find option 1 better, right? 

If so, I definitely agree (option 1 is my preference if those are my only two options) and fully hear that forcing everyone to accept the nav is hidden in conversation view is not acceptable.

**Comment by leggett** [comment]
I fixed this in v2.1.10. The label list stays visible but is dimmed 50% and I hide the unread counts. I undo those two things when you hover over the nav.
