### ISSUE TITLE
Low Info density of the inbox

### ISSUE THREAD

**Issue by scottjenson** [leggett/simplify#331]
I'm one of those weirdos that works hard to keep my inbox clean and what is there is important to scan quickly. The spacing on Simplify is beautiful but its also quite large, turning Simplify off I'm seeing 18 vs 12 messages or 50% more. Note I'm also using priority inbox which of course, also costs me some space.

I appreciate this is a philosophical issue but it one that is important to me. Could there be a 'cozy' setting?

**Comment by leggett** [comment]
I went from 16 to 13 items when I toggle Simplify off/on in a sectioned inbox setup at default resolution on a mac. 

This is caused by three things: 

1. Simplify makes the line height a little bigger
2. Simplify adds space between sections 
3. Simplify adds date grouping

I'm not sure I want to get rid of any of these. Maybe I could offer a setting to reduce the line height back to what it was... but that isn't going to get you back many messages. At most, 1-2. And I don't think it is worth that.

If you use Gmail's compact density, I respect that for line height. I wouldn't want to increase the spacing for that density because people use that setting because they _don't_ want density. But I could make it more dense and make the date groups and section spacing smaller with this setup.

**Comment by leggett** [comment]
P.S. It also might jump that much for you if you use reading pane where each item takes up multiple rows. If that is the case, you could try to turn off reading pane for a bit where you'll definitely see more messages in the inbox.

**Comment by scottjenson** [comment]
Reading your comment, I turned Simplify off, went into Gmail settings, chose the compact view and turned off empty headers for priority view.  Turning Simpify back on was much better, as it significantly improved the number of messages I can see.

**Comment by leggett** [comment]
Cool... You should be able to do that without turning off Simplify too. Was that not possible or did I make it sound like you'd have to disable Simplify to adjust it?

**Comment by scottjenson** [comment]
No reason, I was just comparing the differences
