### ISSUE TITLE
"Attach file" uploads file greater than 25MB - action not clear, or unexpected

### ISSUE THREAD

**Issue by Kw-git** [leggett/simplify#357]
Attempting to attach a file >25MB from Google Drive using "paper clip" attach icon. 

As hoped for, a message popped up that "as the file is greater than 25 MB, a Drive link will be (created)" - much to my surprise, I saw an active progress bar on that same message, suggesting that a file was being uploaded.

The source file for this test was already on Google Drive. Me expectation at this moment was simply that a link to the file would be inserted, and nothing else.

My environment for this particular test was a ChromeBook.

**Comment by leggett** [comment]
I believe this is working as intended but is a bad experience because of a related issue: I hid the "Add Google Drive" file (#358) under the overflow menu (to the left of the delete draft button in the bottom right). When you use the paperclip, it will re-upload it even if the source file was in Google Drive already. 

Please re-open or comment if you think I got it wrong.

**Comment by leggett** [comment]
P.S. I didn't do anything to change how this works... I'm just moving the existing buttons around for the most part.

**Comment by Kw-git** [comment]
My bad - I had never used the "paperclip" attachment capability with Drive files, so I was not aware how this button would behave in conjunction with a Drive file. Entirely ok to close! :-) MANY THANKS for responding!
