### ISSUE TITLE
[v2] Extra left padding generated sub 748px wide

### ISSUE THREAD

**Issue by PhilEv90** [leggett/simplify#371]
The following div is getting extra padding in the email list, when the size of the page goes below 748px. 
That padding gets bigger the narrower the page is. 
Windows 10, Brave. 

![image](https://user-images.githubusercontent.com/42434943/92204101-5291ce80-eeb5-11ea-8a53-3f654f572230.png)

Example at 530px wide:
![Annotation 2020-09-04 140623](https://user-images.githubusercontent.com/42434943/92205287-eb294e00-eeb7-11ea-88b5-608253db79e5.png)

**Comment by leggett** [comment]
But you can't really use Gmail sub-800px. Right? I'll fix this eventually. 

Notes to future self:

- I probably need to set resolution specific rules to zero out the left/right margin below 800px. 
- I should also use a min() on the max-width for conversation view so it can be less wide when the window is less wide. HTML emails will still scroll horizontally.

**Comment by PhilEv90** [comment]
Thanks, you're correct.
I only keep it narrowed to see any emails coming through for when i don't
see the notification.

**Comment by leggett** [comment]
I finally added bare-minimum support for this (pegging the left-margin at 0 below screen width: 775px). A lot of things start to break below this screen size that I'm not trying to fix because there really isn't enough room for Gmail to function. But this will let you do basic things. Update is in v2.3.8
