### ISSUE TITLE
Scrolling glitch while in inline reply

### ISSUE THREAD

**Issue by jayarr100** [leggett/simplify#374]
I've noticed consistently across both Windows and Chrome OS that if I'm in the midst of writing an email as a response — in the inline editing interface — and if the thread is long enough that the top of the response area hits the top of the window, I get a funky scrolling glitch wherein trying to scroll upward (higher in the thread, above my current response) creates a weird jittery effect.

If I scroll _fast_, I can get past it. But standard scrolling gets stuck in that loop.

It's a bit hard to describe, but I think you'll see what I mean in the attached screengrab video.

[simplify-scrolling.zip](https://github.com/leggett/simplify/files/5176808/simplify-scrolling.zip)

**Comment by leggett** [comment]
Yup, this is actually a Gmail bug. If you disable Simplify, I believe you'll still see it.

**Comment by jayarr100** [comment]
Huh — curiously enough, it seems to be specific to the extension for me. When I disable it, I can't make the behavior happen. As soon as it's back on, though, it shows up again, very consistently.

Just for giggles, I tried testing it with Simplify v1 back active in place of v2, and it doesn't happen for me there, either.

**Comment by leggett** [comment]
Ok, I'll look again. Thanks for the report!

**Comment by leggett** [comment]
Ok, I figured it out. Fix will go in next release for non-dark themes. For dark themes, this basically means I need to rebuild inverting messages. 

If anyone is curious, it is because I use `filter: invert(1) hue-rotate(180deg);` to invert messages and that breaks position:fixed. Yay CSS. https://stackoverflow.com/questions/52937708/css-filter-on-parent-breaks-child-positioning/52937920#52937920

**Comment by leggett** [comment]
I made this better in all themes for v2.1.11.
