### ISSUE TITLE
Expanding side menu bar makes for awkward navigation

### ISSUE THREAD

**Issue by JamesKumeroa** [leggett/simplify#377]
Accessing a Room or a Chat from the new side menu is awkward. I have to move my mouse up then down then up again as the menus expand. Would be good to be able to adjust the size/position of these menus to a fixed space.

![market](https://user-images.githubusercontent.com/70552262/92346621-67729a00-f121-11ea-83c9-fedb3e0f4fe8.png)

**Comment by leggett** [comment]
Thanks for the report James. I agree. 

**Some options:**

1. Adding drag-to-resize to the sections as you suggested might work but it requires a fair bit of work from the user and may not do what they want if their window changes size (the size would likely need to be a % of the screen height). So I don't love it by itself...

2. I could add drag-to-resize + good default sizes based on contents. But I can only see your labels. The chat and rooms lists are actually iframes on a different domain. I could ask for access to those domains and report the content back to Gmail. So maybe...

3. I could do something like the old Gmail chat roster (bottom tabs) and let you only show one thing at a time (chat or rooms) but that might be annoying if you're using the rooms. 

4. I could keep what I have now but make the expansion happen on click instead of hover (on a new button or maybe the section title). This lets you easily set which is your primary section and which ones are your secondary. It is a bit hidden and it would mean I would have to un-hide the Mail section title (right now I hide it).  

Thoughts? Other ideas?

**Two band aids to try while I figure something else out:** 

1. Minimize the Meet section. I keep the two buttons visible in the minimized state.
2. It is less awkward if you enter the section from the right rather than above or below.

**Comment by leggett** [comment]
Finally killing this in the next update. It was a bad design and I should have killed it right away. Apologies for the delay.
