### ISSUE TITLE
Top margin above categories is gone on home page

### ISSUE THREAD

**Issue by shenghan97** [leggett/simplify#407]
The tabs for Gmail categories (e.g. Primary, Social) are being displayed right next to the top bar with no space in between. The weirdest thing is, it's only happening to only one of my accounts. The other one is fine.
 
Does anyone know a possible explanation for why this could happen?

**Comment by shenghan97** [comment]
I just found out the reason. It seems like if enabling either the Reading pane or input tools will trigger this bug. Those features will add buttons to the top bar, which might break the underlying CSS overrides. Hope to be fixed soon!!! Thank you so much.

**Comment by leggett** [comment]
This is intentional and unavoidable.

The margin above the tabs is much less if the reading pane is enabled and set to "No Split" as the tabs are _outside_ the scrolling area in this setup and thus, the extra top margin would be constant and reduces the scrollable area. 

When the reading pane is fully disabled, the tabs are part of the scrollable page and the top margin is only there when you are scrolled to the top (not reducing the scrollable are).
