### ISSUE TITLE
no collapsed search

### ISSUE THREAD

**Issue by Vad1mo** [leggett/simplify#408]
I using search quite often and would like to keep it open all the time. It would be nice if there was an option for that in the configuration.

**Comment by leggett** [comment]
The search box is still there and you can click on it. It is just invisible. Here is a screenshot to show you where it is:
<img width="881" alt="Screen Shot 2020-10-06 at 9 22 07 AM" src="https://user-images.githubusercontent.com/8763662/95229596-9d08b280-07b5-11eb-9705-259a272d3559.png">

When you hover over it, you will see the search button. You can also use the ` / ` keyboard shortcut to focus search. I added the visible search button for those that thought it was removed all together.

**Comment by leggett** [comment]
P.S. You can only click on the part of the search box that isn't covered by the action buttons. I wrote more about why I built it this way in this post: https://simplify.substack.com/p/search-navigation-and-add-ons-oh

**Comment by weezer23** [comment]
I think @Vad1mo and I have the same issue. I use search a lot. However, since our company transitioned to Google Chat, there's an added status dropdown in the same area of the search and pagination. Hence, the search is not clickable. Good thing there's the `/` keyboard shortcut.

![simplify](https://user-images.githubusercontent.com/72718810/95700140-e0ad6180-0c78-11eb-8891-fe011c4c3073.gif)

**Comment by leggett** [comment]
That's Simplify v1 not working with the new Gmail. Email me at hi@simpl.fyi and I can add you to the v2 beta that is compatible.

**Comment by Vad1mo** [comment]
@weezer23 I am using keyboard shortcuts to open the search input field.
