### ISSUE TITLE
Can't insert signature while composing email

### ISSUE THREAD

**Issue by SoheilSalehian** [leggett/simplify#423]
When I try to open to insert a signature manually while composing an email, the menu doesn't show anything:

![image](https://user-images.githubusercontent.com/3534699/98296783-6de68c00-1f81-11eb-9be6-81d48733768c.png)

cheers,
S

**Comment by leggett** [comment]
Thanks -- I see it.

**Comment by leggett** [comment]
Turns out this is a Gmail bug that Simplify makes worse by hiding the "Insert signature" button. I'll probably not hide this button by default to get around it but I can't hide the button and have it work.

Repo steps for Gmail without Simplify:

- Disable Simplify
- Reply inline to a message
- Expand the nav and add-ons 
- Make the window narrow enough that the "Insert signature" button goes into the more menu (...)
- Click on more menu > Insert Signature and see that nothings happens

**Comment by SoheilSalehian** [comment]
Ah interesting, it makes sense as I have seen it work with Simplify now as well. Thanks again!
