### ISSUE TITLE
Red highlighting of text

### ISSUE THREAD

**Issue by group7access** [leggett/simplify#483]
Hi Michael. This is the first time I have had the red highlighting of text. I don't want to create more work for you at this point, and maybe it was just user error, but I'm reporting it anyway.

SCENARIO
I had clicked on a mailto link which opened a new tab in Chrome to compose. I typed for a while (long enough that it auto-saved to draft) and when I got to the end and typed "Rob", I instinctively hit Enter to go to a new line, but decided to hit backspace as I really didn't need the new line. Perhaps I also hit another key that is close to my Backspace key at the same time - not sure.
![red-highlighting-in-simplify](https://user-images.githubusercontent.com/70614907/107098964-1f41cb80-67d6-11eb-94fa-cd65a832009a.gif)

**Comment by leggett** [comment]
Thanks for the report! 

I thought I fixed this recently, but clearly not. The problem is the clicking on a mailto link and that opening a compose window in a new Chrome window/tab.

Just to be sure, what version of SImplify do you have?

**Comment by group7access** [comment]
I'm on Simplify v.2.1.25, however, it may have just updated when I tested again and...  could not replicate the red highlighting.

What I did notice this time is that when I discard my draft from the new mailto-initiated tab, the message stays on my screen... so then I disable Simplify and repeat the test with stock Gmail and experience the same behaviour, so forget I even mentioned it ;) - but since I captured a GIF of it, I'll share it anyway! (But, seriously, I believe this case is closed.)

![mailto](https://user-images.githubusercontent.com/70614907/107105983-d2b6ba00-67ee-11eb-9101-0d936b596954.gif)

**Comment by leggett** [comment]
This was fixed a while back. And I added further improvements in the case of the mailto popout in v2.3.7.

**Comment by andymand** [comment]
Just saw it again.  I typed a three-period ellipsis and accidentally hit enter (breaking the ellipsis apart) -- because I thought I was texting my wife, not emailing -- and got the red highlight.  I tried (admittedly not very hard) to get rid of it, but couldn't and figured you'd wanna know.

![image](https://user-images.githubusercontent.com/51393001/119134805-9d378480-ba0b-11eb-989f-ad2ae24df0ca.png)

**Comment by leggett** [comment]
That means I'm not observing the compose. How did you get into this compose?

**Comment by andymand** [comment]
- I went to the webpage shown in the screenshot
- I clicked on the toolbar icon for the Share link via email extension (https://chrome.google.com/webstore/detail/share-link-via-email/ejdbkikfbnnhmachnnomjfgjbgkcnjkb) which opens a compose dialog
- I added the text in the screenshot

and you know the rest of the story.  :)

**Comment by leggett** [comment]
Thanks for the details. I can't seem to repeat this issue though even with that extension... what version of Simplify do you have? 

If you are on Edge, you are probably on v2.3.11. I fixed a few things around popped out compose in v2.3.12. v2.3.13 is the current version -- Microsoft is super slow in approving updates. I expect it to be out in a few days though and can ping this issue when it updates.

**Comment by andymand** [comment]
I'm running a Chomebox which runs Chrome (as you likely know :) -- Version 90.0.4430.100 (Official Build) (64-bit) -- and I'm on Simplify v2.3.13.

**Comment by leggett** [comment]
Hmm, ok, that isn't it then. Three possibilities here:

1. Simplify isn't running at all (what I think is happening)
2. Simplify is running but exited early thinking this was a different special case (I shut Simplify down in print view for instance)
3. Simplify is running but didn't detect the composer

(2) and (3) are unlikely. I think (1) is happening as the composer is not inset and floating in the window -- it goes all the way to the top of the window. I only revert to full-bleed when the window is less than 650px tall. You could also check and see if the compose actions are hidden behind a ">" button.

The next question is: was this a one off, or does it happen every time? If it happens every time you compose a message through this extension, it would help to have the URL for the compose. It would also help to know if it happens when you pop-out a composer (you can do this with the `d` shortcut)

When I use that extension, this is the URL I get the following which includes `tf=cm`:
`https://mail.google.com/mail/u/0/?fs=1&tf=cm&=1&to&su=New+York+Times&body=%0Ahttps://www.nytimes.com`

When I press `d` in Gmail to start a new message in a new tab, I get the following which includes `view=btop`:
`https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=ops2cvpehp6#cmid%253D2`

**Comment by andymand** [comment]
Hi Michael- FWIW, I haven't seen this in months, so I'm going to assume
that it's fixed  :)

Sent via Gmail
