### ISSUE TITLE
Ads are back on Promotions and Social tabs

### ISSUE THREAD

**Issue by danielanewman** [leggett/simplify#485]
Seen for the first time today, v 2.2.0 Beta

**Comment by danielanewman** [comment]
Update! They disappeared after a refresh, so this might be an "on first run" thing?

**Comment by leggett** [comment]
Yup -- one of the last bugs I fixed was about this too. Until a couple days ago, if you switched your inbox type TO a tabbed inbox without reloading, Simplify wouldn't check for ads because they are only on the tabbed inbox. Now it checks if it is a tabbed inbox every time you switch back to the inbox.
