### ISSUE TITLE
Themes are applied only on message pane

### ISSUE THREAD

**Issue by csebareg** [leggett/simplify#492]
Themes are applied only on message pane.
Please see attached screenshots.
I used until now "Dusk" background color, but with simplify Inbox pane remains white, and left pane text color is white too.
![desk](https://user-images.githubusercontent.com/78732610/107212629-e725cd00-6a0f-11eb-8979-ee5fd1c40faf.png)
![dusk](https://user-images.githubusercontent.com/78732610/107212644-eee57180-6a0f-11eb-9e55-ec2fad44c175.png)
![wood](https://user-images.githubusercontent.com/78732610/107212647-f0169e80-6a0f-11eb-8d46-161e78f66148.png)
![eggplant](https://user-images.githubusercontent.com/78732610/107212653-f278f880-6a0f-11eb-8f6e-a1916ee7c15f.png)

**Comment by csebareg** [comment]
Above screenshot in vertical split pane mode

**Comment by leggett** [comment]
Thanks for the report and screenshots. 

This is intentional. I tried a lot of things in this case and felt this was the best way to go. Making the nav/list transparent makes it harder to read the messages AND makes it harder to achieve this view (as I move a lot of different elements into the list view like search, search chips, tabs, one boxes, the "Did you mean" bar, and more). 

I will continue to monitor feedback to see if I should revisit.
