### ISSUE TITLE
Update email category to newly visible categories

### ISSUE THREAD

**Issue by DaveVilleneuve** [leggett/simplify#516]
With Trips, Finance and Purchases now visible (awesome!), the only two ways I found Gmail allows you to set the category is through manual drag and drop or with rules in place to filter to a specific category. 

The 3 unhidden ones are not available to select for a filter and the drag and drop does not function on the new categories.

![Filter](https://user-images.githubusercontent.com/57647797/107733355-d653b080-6cc8-11eb-977c-c51a783713c7.jpg)

**Comment by leggett** [comment]
Correct. 

I can't do this kind of thing without API access to your email (something I'm trying to avoid). And even if I had that, I'm not sure I could interact with those categories / labels (Trips is a system label instead of a category for some reason).

I'll flag this as something to maybe come back to if I ever offer extra functionality with API access.
