### ISSUE TITLE
White bar around Nav menu when clicked

### ISSUE THREAD

**Issue by Julian88Tex** [leggett/simplify#517]
A white bar appears around the nav menu whenever it is clicked. Hovering over nav icon (hamburger) does not produce **white** bar.

![Screen Recording 2021-02-11 at 9 53 54 PM](https://user-images.githubusercontent.com/459099/107735265-27a57500-6cb4-11eb-9b65-7f8e88ee88ab.gif)

**Comment by leggett** [comment]
I can't reproduce this. What browser are you using? 

It might be caused by Gmail being in this borked theme state it falls into sometimes where it hasn't fully switched to the dark theme. If you hold down shift and press the refresh button, it should fix the theme issue. But not sure if the border issue will go away.

**Comment by Julian88Tex** [comment]
@leggett sorry should have included more details like in Issue. Something else important to note is that it occurs now only on my Google work account. The original gif is from my personal account so it appears to be intermittent. I'll add additional details if I see a pattern.

- macOS 11.2.1
- Chrome 88.0.4324.150
- Simplify v2.2.2
- Dark Reader 4.9.27 extension is installed but was turned off for gmail

**Comment by leggett** [comment]
I believe I fixed this a while back. Let me know if you still see it.
