### ISSUE TITLE
Support text buttons

### ISSUE THREAD

**Issue by dtsn** [leggett/simplify#52]
![Screenshot 2019-04-12 at 10 10 05](https://user-images.githubusercontent.com/354263/56026084-5561b180-5d0b-11e9-9e3e-0a6b1bbb96d3.png)

I have the basic Gmail theme and when looking at an email the action buttons overlay the search. I can fix this and raise a PR but first wanted to clarify what you mean by 'hidden' in the following lines of the CSS.

`/* Hide all search form buttons except search button when search is hidden */
/* For non-english interfaces, may break as this class name gets changed often */
html.simpl.hideSearch #gb form:not(.gb_oe) button:not([aria-label="Search Mail"]):not(.gb_Ue) {
	display: none;
}`

My fix was to just show the icon when on that screen if the max-width is less than 1000px.

**Comment by leggett** [comment]
If you switch to using icons for buttons instead of text labels, it will work (Settings > Button labels > Icon). The problem is your action bar is much wider than what I designed for and when search is expanded, it is overlapping on top of the pagination controls. 

Other fixes to address this and support text buttons:

- Detect the use of text labels and always hiding the pagination controls when search is expanded in these cases unless the window is super wide so it can all fit.
- Make the search box non-transparent so when it overlaps with the pagination controls, it doesn't look awful. This would only work in simple color themes as the transparent search box looks really good in the themes and I wouldn't want to lose that.
