### ISSUE TITLE
Support bundles in the Inbox

### ISSUE THREAD

**Issue by leggett** [leggett/simplify#56]
I've been poo-pooing the idea of supporting bundles in Gmail thinking it would be impossible but now I'm starting to think... maybe it would be possible. Just maybe. 

**Supporting it for the inbox category tabs**

- The mail for each tab is loaded in the DOM. I could scan the mail and inject an item in the primary tab at the right time & date of the most recent message. 
- I could also maybe accept settings for when you want these bundles delivered making sure they only show up after those dates.
- Clicking on this item would show the category tab with an added button to return to the primary tab (which had the added bundle links)

**Support for other labels acting as bundles**

- IF a label is set to be bundled and I see messages with that label on it in the inbox, I could hide all instances and show just one item at the location of the most recent message. 
- Clicking on this item would go to a search for that label. Clicking back would return to the inbox. 

**Pairs well with...** - both of these are possible and under consideration but are more interesting to me if the extension has an opinion on which inbox to use. 

- Adding the date groupings
- Sweep button to archive anything not starred

**Comment by leggett** [comment]
I would scan the inbox on load and then set a mutation observer on anything being added to the dom. It appears that the inbox is never unloaded when doing a search, going to a label, or opening a message. 

I'd need to add an attribute (like bundle) to the item row as classnames are over-written when you go in and out of a message.

Going to settings appears to unload the dom erasing any changes made and would require a rescanning of the inbox but going to settings isn't done as often.

**Comment by leggett** [comment]
To be clear, this would be desktop only and I still worry about having the inbox on desktop diverge a lot from mobile. Bundling the category tabs doesn't seem that big of a deal. But doing it for labels and/or having options for when the bundles show up will cause them to be quite different.

**Comment by jcgoble3** [comment]
I would love this. However, it is useless to me without label bundling. I do not trust Google's algorithms to not hide critically important and urgent emails from me in the category tabs (especially because such emails, for me, are sometimes general announcements sent to a student mailing list) and so I do not use the categories. I do, though, bundle all messages from my various programming language mailing lists (Lua, several Python lists, etc.) into individual label-bundles to keep things neat and orderly. I also have a few other automatic bundles set up.

I am one of the few that still has a functioning Inbox tab open in my browser, on both my Windows desktop and Ubuntu laptop. I am delaying Windows and kernel updates, respectively, because I don't want to shut the tab down. I also obtained an older version of the Inbox app without the kill switch from apkmirror, and I'm seriously considering learning how to write an Android app by programming my own Inbox substitute for when the APIs that make Inbox work are shut down.

In case you can't tell, Inbox is sort of important for me.

**Comment by leggett** [comment]
Label bundling will be the hardest but may be possible. The biggest problem I can see is you will have to have those messages not skip your inbox (as I can only bundle what I see in the inbox). That will lead to your inbox on mobile being a bigger mess.

The inbox categories are interesting because they take the number of messages loaded in the DOM all at once from 100 to 500. I can bundle inside those category tabs and maybe even across them so long as labels are being applied via filters. And your mobile inbox will be less different... maybe.

I won't know for sure until I start digging into it and seeing what I can do. A number of other things in front of this task but I'll get to it.

**Comment by onefork** [comment]
@leggett Just want to say thank you. Gmail without bundles is really killing me...

**Comment by SullieLore** [comment]
In relation to this problem and others like it, I would highly recommend adding a small icon to the settings of Simplify Gmail for "beta testing". That you might be able to get additional real-world feedback coming in without giving your main product a rushed look. I would definitely be keen to test out bundles as it's the one key thing missing from my Gmail now. My mobile app is already a mess so I usually just use it for Priority emails at present... then again, if you decided to build a paid iPhone app called '**Inbox2**' I wouldn't complain.

**Comment by klangenbach** [comment]
> @leggett Just want to say thank you. Gmail without bundles is really killing me...

This a thousand times. My inbox is a hot mess right now and takes me 10x as long to clear it out.

**Comment by bgupta** [comment]
> Label bundling will be the hardest but may be possible. The biggest problem I can see is you will have to have those messages not skip your inbox (as I can only bundle what I see in the inbox). That will lead to your inbox on mobile being a bigger mess.

Well, right now for many of us our inboxes on desktop and mobile are a hot mess. If I can bring label bundling to the web/desktop, where I spend most of my time reading and dealing with work email, that would sort out 95% of my problems. Please note, even now with my workaround using "labels that only appear with unread emails" (which really is only a shadow of the power of a bundle), it is still an entirely different experience on mobile, and mobile has become near useless for dealing with email. Down the road, I expect it shouldn't be too hard to bundle a custom browser w/ the chrome plugin as an android app if you really want to help (some of the) people on mobile.

The longer I go without bundles, the more confused I am by google's decision to kill inbox and not bring all inboxes features to gmail. I am now spending triple the time on email yet falling ever further behind. (And am much more likely to not see important emails in a timely fashion.)

**Comment by MormonYoYoMan** [comment]
The links I've tried, doesn't get me to a download of any kind....the best screen I've found (the final location of the link's threads) gets me to a peaceful forest lake.  I'm assuming that's where I should take my Gmail account, put it in a burlap sack, and throw it in the lake?

**Comment by Exerosis** [comment]
(Sorry to bump an oldish post)

Is there a reason that some of us don't try to get a group together and remake some form of Inbox using the Gmail API or something along those lines? I feel like trying to patch Gmail is never going to net something like Inbox. Also, I think expanding on the integrations with services that typically send you an email(e.g., the airlines sending boarding passes and itineraries and what not) would be cool. (One click check-in and then directly import the boarding passes to google pay for example)

Anyway, if anyone wants to talk about it more let me know and maybe join this discord: https://discord.gg/Yzd3Kf5

**Comment by leggett** [comment]
After looking into this a lot and trying to build it twice, I'm going to give up on trying to add this (again). Maybe I come back to it some day as other things settle down. I'm also still hoping that Gmail adds the functionality itself. Once Simplify v2 is launched, I hope to try and get ahold of someone on the team to petition for them to prioritize it if they aren't already. 

The good news is there is a pretty good solution out there: [inboxymail.com](https://inboxymail.com) and it is compatible with Simplify. Inboxy is well written ([source code here](https://github.com/teresa-ou/inboxy)) and works about as well as it can in my testing.

The two issues that lead me to not add this to Simplify v2 (Inboxy has both of these issues):

1. **I can only bundle what I can see.** If you have more messages that are in your inbox but are are on the next page of your inbox, they will not appear in the bundle. Two solutions to this are: 

(a) Live with it: Add a "View all" link on the bundle -- this is what Inboxy does and similar to what Google Inbox did when the bundle had more than 25 items or 

(b) ask for API access to your account so I can see more than what is on the screen -- this is asking a LOT more trust of the user and there no guarantee this will work well unless I build a whole extra layer to cache more than 100 messages so I can cache the grouping. 

2. **You can't *really* reorder the threads into groups.** You can change what the user sees but Gmail still considers everything in the original order. And this breaks pagination. For me, the whole point of bundling is to read a group of messages together (open the first and zip through the set). I [wrote up a possible solution](https://github.com/teresa-ou/inboxy/issues/48) to this for Teresa but it is a bit messy in my opinion and I don't want to try and support this along side all the other modifications I'm adding.

**Comment by leggett** [comment]
I'm just going to close this issue for now but I'll re-open it if I ever pick it back up.

**Comment by leggett** [comment]
I have picked this back up and am determined to ship some version of bundles in Simplify before the end of the year.

**Comment by jcgoble3** [comment]
Thanks for looking back into this. There was some work done by @boukestam and @russelldc shortly after my original comment above, and I took that work and pared it down to just the essential function of bundling. You can check out my repo at https://github.com/jcgoble3/gmail-bundling where I did my work, and the README there links back to where I forked from. It's all MIT licensed, so you're welcome to take and use whatever code you see fit. I haven't published to the add-on stores, but I do have signed Firefox extensions on the releases page that I use and you can try out (or you can clone and load unpacked in Chrome). There are some bugs and it definitely isn't polished, but it mostly serves my purpose and it's worth a look. I would be happy to see a higher-quality version though, as I have had very little time to work on it between school and internships.

As for the three issues referenced above in https://github.com/leggett/simplify/issues/56#issuecomment-657266519:

1. That's fine, I keep my Gmail on 100 per page anyway and never have that much in my inbox. Right now I have 29 emails in my inbox, of which 2 are unread. I only keep emails in my inbox after reading if I know I need to refer back to them later, and then only for as long as I actually do (e.g. shipping emails are kept until the package arrives and then archived after delivery).
2. Per number 1, pagination is not an issue for me as everything is on one page anyway. I also am not concerned about how bundles are ordered relative to unbundled emails (my custom extension already gets this wrong in many cases).
3. It already looks a lot different on mobile (since I use my custom extension on desktop), but I also don't do serious inbox management on mobile, so I'm not terribly concerned about that. As a long-term thing, a mobile app might be something to consider, although that would require API access since it would have to be its own thing instead of a layer on top of Gmail.

**Comment by leggett** [comment]
Thanks for the link. I'll take a look. 

Pagination and the keyboard shortcuts working is a must in my eyes. I've resigned myself to basically build custom handlers for pagination and J/K and up/down in both the inbox and conversation view.

**Comment by leggett** [comment]
Making a lot of progress. Still a lot to do. 

I'm going to look for a min-viable version that I can launch to the canary channel while I keep working on it. One of the big corners I'm cutting is opening bundles by navigating to a search instead of showing them inline. I also decided that showing profile photos in the inbox is a must so I've got that working too now. This is turning into quite the update! :D

![image](https://user-images.githubusercontent.com/8763662/136903370-bbfd78a2-8393-466f-8d3b-97915aea8f40.png)

**Comment by erikgeurts** [comment]
Frankly, I've never figured out what all the excitement about "bundles" is about, or what the use case might be. But then again, I never was a big fan nor user of Inbox.

**Comment by leggett** [comment]
That's ok. It isn't for everyone. And it will definitely be an option and probably off by default.

As far as the value prop, it is a better version of filters or of the inbox tabs. A way to both take certain classes of emails (notifications from a service, a newsletter, social updates, promotional email, etc) and (a) keep them from taking over your inbox as filters can do when you label and archive and (b) not having them be totally out of sight. 

The inbox tabs sort of do this but (a) only for Gmail's 4 categories and not for user labels, and (b) it is always at the top which misses out on using placement in the inbox to give you an idea of when the latest message was and (c) doesn't show as much information about what is in the tab as a bundle in the inbox can. 

Other bundling features that I hope to bring over:

- The ability to schedule when the bundle is delivered (as new mail arrives vs every morning at some time vs once a week)
- Actions to sweep away (archive or delete) any non-starred emails in a single click
- Better visibility into the filters that put emails in a label (this may not be possible with the current permissions)

**Comment by erikgeurts** [comment]
Ok, thanks for clarifying. With my inbox(es) always being at (close to) zero, it wouldn't be very useful anyway in my case.

Definitely sounds like something that I would not switch on, but I can see how it might be useful for others.

**Comment by leggett** [comment]
For inbox zero types, I think the scheduled delivery is what might make it useful. 

Take promotional mail. Very unlikely that it is timely. I used to have that bundle delivered once a week on Saturday morning. I'd open it, skim, maybe open one or two, and delete all.

Without bundles, to keep inbox zero, I was processing those emails as they came in.

**Comment by erikgeurts** [comment]
I see how scheduled delivery would be useful for others, but it's definitely not for me. I've got a personal mailbox and two mailboxes for my two business. Any promotional mails (a nice word for semi-spam) in my personal mailbox, I won't see during business hours since I simply don't have my personal Gmail open while working. And if something I don't like arrives in my work mailbox, I will unsubscribe and/or mark it as spam, so I'll hopefully never see it again.

**Comment by samskiter** [comment]
So, are bundles implemented? I just installed simplify but didn't see any...

**Comment by leggett** [comment]
They are on the v3 beta: https://beta.simpl.fyi

I'm working to get v3 out to all users and all browsers ASAP.

**Comment by seeruk** [comment]
Hey there, I've been using the beta / canary versions of Simplify Gmail for a long time now on Chrome (and it's awesome!), but I'm wondering if there's also a v3 version available somehow for Firefox? I'm thinking about jumping ship with the direction that Google is taking Chrome and Manifest V3, but I've grown very accustomed to those bundles!

**Comment by leggett** [comment]
@seeruk Not yet but VERY soon. I'm getting really close to launching v3 out of beta to all users and all browsers. I'm working to get it out by the end of the year and might try releasing it on Firefox first.

**Comment by leggett** [comment]
I'll add that I've been waiting on Firefox to add better support for Manifest v3 (mostly there) and [CSS :has()](https://caniuse.com/css-has) (finally going live in Firefox v121 which is scheduled to be released on Dec 19th, 2023).

**Comment by stewartbutler** [comment]
Been using the bundles feature in beta for a while now, works great so far! 

I'm not sure if this is the right place for it, since it seems somewhat feature-request-y, but the one feature that seems to be missing is an option to turn the 'sweep' function from 'archive' to 'mark as read + archive', so that the unread mail won't prevent the label in the sidebar from collapsing. 

That seems to match the way I recall the old Inbox UI presented things (though IIRC inbox didn't really mark them as read under the hood).

Any idea what the LOE of adding that would be? I'd imagine it would increase the time required to apply a sweep (since you have to chain the mark unread and archive commands together) but it seems like it is something that could be added as an options toggle, and at least in my workflow it'd save a lot of time -- the UI tends to jump around a good bit if you mark an entire bundle as read before archiving it.

**Comment by leggett** [comment]
- Google Inbox never marked items as read when you swept a bundle or date group. But it also never had an option to dynamically show labels if they have unread mail. 
- This shouldn't be too hard technically as I already have support for holding messages where they are after you mark them as read/unread so the bundle doesn't change out from under you
- The hard part is finding an icon that means archive + mark as read (I don't want it to be an option on what archive does) and not overwhelming users with too many options/actions 
- I could add the ability to pick what actions you see on a bundle like I do with date groups now and it could be a separate action that is hidden by default

**Comment by leggett** [comment]
PSA: **Bundles are now supported in Simplify v3** which launched out of beta in the new year! And it has full keyboard-shortcut support.

- You can see a [tour of bundles in this video](https://www.youtube.com/embed/f_jel2PY9O8?rel=0&showinfo=0&vq=hd1080)
- And a tour of all [what's new in Simplify v3 in this video](https://www.youtube.com/embed/CM5hVyzRm4Q?autoplay=1&rel=0&showinfo=0&vq=hd1080)

There is still more I want to do to make bundles as powerful as they were in Google Inbox (e.g., snoozing, scheduled delivery, maybe even showing filters inline, etc). But I'm happy with where it is at.
