### ISSUE TITLE
Emails disappear from the Promotions tab until a refresh of Gmail is done

### ISSUE THREAD

**Issue by CliffWade** [leggett/simplify#567]
I'm not 100% sure if this is a Simplify issue or not, but I'm going to report it here just in case. 

When using Edge and Simplify, I can see when I have a new email in the Promotions tab. When I click the Promotions tab, the email disappears, as if there really wasn't one and it was a false notification. 

I then refresh Gmail, and then the email appears in the Promotions tab again and this time remains there when I click Promotions.

Oddly, this only seems to happen with the Promotions tab and it only does it when the original email comes in. Once it disappears and once I refresh, it doesn't happen again until the next email comes into the Promotions tab. 

I keep forgetting to try and get a video of it happening, but will certainly to do so next time if I remember. 

If there's any further information you need please let me know and I will certainly try my best to get whatever I can.

Edge version: Version 90.0.818.14 (Official build) beta (64-bit) - While this is a Beta information, it seems to happen in the stable version too as I've tested it there.

Simplify: 2.3.7

![Screenshot 2021-03-25 152555](https://user-images.githubusercontent.com/4813948/112531834-6d0e9500-8d7e-11eb-9b7d-ebd0680ab115.png)
---
System: Mozilla/5.0 (Windows NT 10.0)

**Comment by leggett** [comment]
Thanks for the detailed report Cliff. Apologies for the issue.

- I do believe this is a Simplify issue. Gmail has started putting non-ads above the ads or sometimes in the same table with the ads (something they didn't do before). Simplify was hiding the table that had the ads before. 
- The good news is a fix is landing today. Instead of hiding the table, I'm only hiding the ads now.
- The bad news is Edge usually takes 7+ days to approve updates so it will be a bit longer if you are using Simplify from the Edge store instead of the Chrome store (you can use either on Edge).
- Once you get v2.3.9 (v2.3.8 was to canary only, so you didn't miss a version), let me know if you still have any issues.

**Comment by CliffWade** [comment]
I didn't want to file a new bug report about this since I had filed this one a week ago and it was fixed at least for a few days. 

But as of yesterday, maybe the day before, this issue has started up again. 

It's completely random, doesn't happen every time and again seems to be isolated to just the Promotions tab. 

I can't 100% reproduce it every time, and I certainly don't get a lot of emails and especially not many that go to my Promotions tab. 

I wish I could provide more information to really be beneficial to you via this bug report.

I do know I'm on the latest Simplify version which is currently: 2.3.10 and while I do use Edge, I get the extension from the Chrome store.

**Comment by leggett** [comment]
Well that's a bummer... I thought I knew what the issue was and that I had fixed it. So either the issue is something else or I failed to fix it. 

Can you email me a system report so I can try to duplicate your set up? There are instructions on [simpl.fyi/support](https://simpl.fyi/support)

**Comment by leggett** [comment]
Config: 
- Simplify v.2.3.10 
- Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup defaultTheme hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg lowDensity matchFontSize minimizeChat msgWidthSm navOpen newUI simplify 
- System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.41 Safari/537.36 Edg/90.0.818.22 
- Window: 1920 x 1040 (100pct zoom) 
- Language: en

**Comment by leggett** [comment]
Do you have "Bundling in Promotions" enabled under Gmail Settings > Inbox?

**Comment by CliffWade** [comment]
I do indeed have that enabled. Should that be disabled or will it help to have it disabled? I'm sure that was set years and years ago so I doubt it's something useful to me.

**Comment by leggett** [comment]
If the Top Picks don't feel helpful, then yes, I'd disable it. 

I've been trying to reproduce this today and here is what I notice:

- The item that is highlighted on the Promotions tab is not the most recent promotion... I just clicked on the promotions tab after ignoring it since around lunch. The promotion that was highlighted was from 2pm with several newer ones above it. 
- I find that when I have Bundling in Promotions enabled, I will go to the Promotions tab, the message that was highlighted on the tab is briefly at or near the top and then pushed down when the list is fully reloaded (adding new promotions above it AND the "Top Picks" section)
- I haven't seen Simplify hide anything other than ads so far but I've only been testing for today.

Both of the above are Gmail things and I'm not sure what Simplify could do to fix them other than hide the preview of what is in the Promotions tab (which I don't think is a good idea).

**Comment by CliffWade** [comment]
Awesome. Thank you for the information. I have disabled the Bundling In Promotions option so hopefully whatever issue I'm seeing will go away. 

I appreciate all of your work on this and for replying so quickly every time. Keep making and updating this awesome product and I can't wait until the paid plans go live as I will for sure be supporting it from day one.

**Comment by leggett** [comment]
I'll close for now but let me know if it comes back again.
