### ISSUE TITLE
What does "New option to hide Mail section title (in new nav)" mean?

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#579]
According to the change log for v2.3.11, there is a new feature "New option to hide Mail section title (in new nav)".

What does this do? Could you show a screenshot with this feature enabled and disabled?

**Comment by leggett** [comment]
If you have Google Chat enabled instead of Hangouts or are on a Workspace account, you get a new Gmail nav with section titles above each section including the email section. This option hides that title.

Disabled:
<img width="262" alt="Screen Shot 2021-04-15 at 8 05 29 AM" src="https://user-images.githubusercontent.com/8763662/114892212-685b6080-9dc1-11eb-99b7-98a450d4b211.png">

Enabled:
<img width="279" alt="Screen Shot 2021-04-15 at 8 01 00 AM" src="https://user-images.githubusercontent.com/8763662/114892240-701b0500-9dc1-11eb-967d-d7f2e66c827d.png">
