### ISSUE TITLE
French translation overlaps on menu button

### ISSUE THREAD

**Issue by joachimBrindeau** [leggett/simplify#585]
Hello,

In the french version of gmail the buttons for an email overlap with menu buttons making the menu hard to reach.

<a href="https://ibb.co/SKJNNqB"><img src="https://i.ibb.co/LCvSS41/image.png" alt="image" border="0"></a>

Thank you for this great tool.

Best regards,
Joachim

---
System: Edge + Windows 10

**Comment by joachimBrindeau** [comment]
<a href="https://ibb.co/1bJJgVx"><img src="https://i.ibb.co/TrqqfX5/image.png" alt="image" border="0"></a>

Similar issue this time on a Gsuite account.

**Comment by leggett** [comment]
Thanks for the report. I'm guessing you are using the vertical split pane (messages to the right of the inbox) in both of these, yes? And it looks like you have a pretty small window or maybe you just have the list pane set to be really wide?

Like this:
<img width="1229" alt="Screen Shot 2021-05-13 at 7 10 57 AM" src="https://user-images.githubusercontent.com/8763662/118137761-6c779f80-b3ba-11eb-99f7-446089d80950.png">

**On the first one with the text buttons**, even if I kept it from overlapping with the profile button, you can't see all your actions. You would be better off switching to icon buttons ([Gmail Settings > General](https://mail.google.com/mail/#settings/general) > Button labels > Icons) or in French, ([Paramètres > Général](https://mail.google.com/mail/#settings/general) > Libellés des boutons > Icônes)

**On the second one**, I thought I had the message actions hiding when you hover over the profile menu button so that overlap doesn't happen, but apparently not. Or at least not in this case. I will add that.

**Comment by leggett** [comment]
Ah, I hide the pagination controls on hover. I should do the same to the message actions in vertical split pane:
https://user-images.githubusercontent.com/8763662/118138561-561e1380-b3bb-11eb-844b-34221f9b3f76.mp4

**Comment by leggett** [comment]
Ah, I hide the pagination controls on hover. I should do the same to the message actions in vertical split pane:
<video width="1344" src="https://user-images.githubusercontent.com/8763662/118138561-561e1380-b3bb-11eb-844b-34221f9b3f76.mp4">

**Comment by joachimBrindeau** [comment]
Thank you, switching from text to icon was perfect.
I thought that was a Gsuite option.

I look forward to the fix for the second issue on the vertical split pane. :)

Thanks for the quick answer!

**Comment by leggett** [comment]
I have a fix included in the next update which should go out today.

**Comment by leggett** [comment]
(It will take a couple days for Google to approve the update)
