### ISSUE TITLE
Top margin in "Priority inbox" view

### ISSUE THREAD

**Issue by mmmanson** [leggett/simplify#59]
Hi, great app, better than inbox! 
May you please check top margin in "Priority inbox" view, it's bigger than in the "Default" view, may be invisible tabs add margin ( class=ae4 aDM role=tabpanel).
That would be great, if we may have button "Archive all" in interface, not in far menu like now. (Inbox type -> "Priority inbox". "Everything else" section -> 3 dots -> "Archive all").
Something like in inbox interface, there were check buttons on email groups to archive entire group. 
Thanks for your work.

**Comment by leggett** [comment]
The top margin looks correct to me. If you see something other than this, can you send a screenshot?
<img width="1202" alt="Screen Shot 2019-04-15 at 6 38 27 AM" src="https://user-images.githubusercontent.com/8763662/56137238-35b7cc80-5f49-11e9-9d70-24208263e23b.png">

**Comment by leggett** [comment]
I'm tracking adding a archive all that isn't starred button (just as Inbox would clear all that weren't pinned) here: https://github.com/leggett/simplify/issues/54

**Comment by mmmanson** [comment]
Hello, Michael, thank you for the reply.
My sreenshot is in the attachment.
I see on your screenshot that first section is "important and unread" in my
"Important", may be this is a difference, may be the section "important and
unread" is invisible and add this big margin.

**Comment by leggett** [comment]
I see now. Thanks for the screenshot. You've got your sections set to hide when they are empty (totally reasonable). And right now, the top section is empty and therefor hidden. 

I can't figure out a way to dynamically apply the extra padding between sections depending on that setting. So this is likely to stay this way for now.

**Comment by mmmanson** [comment]
Just to be clear, i find that no margin in original gmail interface
(attachment), and it looks better.
If that helps i'll be happy.

**Comment by leggett** [comment]
I don't like no top margin. It doesn't look good with the white space on the sides you gain from hiding the rest of the Gmail interface. 

But you have extra top margin. This comes from fixing a different problem: that there is no space between inbox sections which makes it hard to see where one section ends and the next begins. 

You are seeing extra top margin due to the added space between the top section (hidden) and the second section (visible). The top section is hidden because you set it to hide when empty.

This added top margin (1em or about 20px) is due to the first section being hidden and is not my intented result. But I don't see an easy way to correct it yet.

**Comment by mmmanson** [comment]
Yes, i fount it.
html.simpl div[gh="tl"] div[role="tabpanel"] {padding-bottom: 1em;}
Looks complicated to fix.
Good job anyway, thank you.
