### ISSUE TITLE
[feature request] Compose new mail button location is too far

### ISSUE THREAD

**Issue by t0mmyz7** [leggett/simplify#602]
Hi

for me, the location of 'Compose' is too far. I use a 24" monitor, mainly I am on the top-left side of the screen while in Gmail

the original location is there, although could be better as well, but the new location is in a corner of the screen I never visit in gmail.

I am not a big shortcut user in gmail yet, so i guess I need to start because that is probably the fastest route there. but... as a productivity improvement, I would suggest:

1. add option to cancel moving it  keep it in the same location, 
2. offer some alternative locations for it like a small + button next to select all/refresh. Or small + about the tabs to the left or right

what do you think?

![image](https://user-images.githubusercontent.com/31729091/127458218-ea514df7-f651-4d44-af64-ba2e10a4abb1.png)

**Comment by erikgeurts** [comment]
Just press C to start composing a new message.

**Comment by t0mmyz7** [comment]
sure, so why have the button at all?

**Comment by erikgeurts** [comment]
Because some people, like those with touch screens, might prefer a button on the screen.

**Comment by leggett** [comment]
You have to have keyboard shortcuts enabled to use `C` and sometimes you just want to click on a button.

Having compose outside of the nav does two things:

1. It puts the compose button near where the new message will show up (in the bottom right corner)
2. It allows me to hide the nav entirely when it is minimized

Similar to other things, I don't want to add an option here as it would impact a lot of things and increase maintenance costs.

**Comment by erikgeurts** [comment]
> 1. It puts the compose button near where the new message will show up (in the bottom right corner)

Actually, I think a lot of people have there compose new message to "full screen" (which isn't 'full' at all ;) ).

**Comment by t0mmyz7** [comment]
I would go for a little + next to select all

and by the way, the fact that the new message window pops up where it does,
bad location choice IMO. I would prefer it to default to full screen mode,
or same location as full screen mode, but hovering over maybe.
But option 1 will be full screen mode for me, is this something you can
consider adding?


[image:
https://iotexperts-web.s3.eu-central-1.amazonaws.com/IoTExpertsLogo.png]

*Tom Zamir | Owner*

*IoT Experts*w: iot-experts.net
m: +972-556-601-239
e: ***@***.***
<https://www.linkedin.com/in/tomzamir/>

**Comment by t0mmyz7** [comment]
What, how, where? :)?

[image:
https://iotexperts-web.s3.eu-central-1.amazonaws.com/IoTExpertsLogo.png]

*Tom Zamir | Owner*

*IoT Experts*w: iot-experts.net
m: +972-556-601-239
e: ***@***.***
<https://www.linkedin.com/in/tomzamir/>

**Comment by leggett** [comment]
> Actually, I think a lot of people have there compose new message to "full screen" (which isn't 'full' at all ;) ).

Defaults are always king. I doubt many even know about full screen compose, much less have it as the default.

**Comment by leggett** [comment]
Set to full screen by default in any compose message:
<img width="428" alt="Screen Shot 2021-07-29 at 1 43 17 AM" src="https://user-images.githubusercontent.com/8763662/127461083-2b50dfa8-571c-4a45-a177-c6352a690e7b.png">

**Comment by t0mmyz7** [comment]
Amazing...

[image:
https://iotexperts-web.s3.eu-central-1.amazonaws.com/IoTExpertsLogo.png]

*Tom Zamir | Owner*

*IoT Experts*w: iot-experts.net
m: +972-556-601-239
e: ***@***.***
<https://www.linkedin.com/in/tomzamir/>

**Comment by erikgeurts** [comment]
> > Actually, I think a lot of people have there compose new message to "full screen" (which isn't 'full' at all ;) ).
> 
> Defaults are always king. I doubt many even know about full screen compose, much less have it as the default.

I've never understood why the Gmail developers thought it was a good idea to make that tiny stamp sized "compose message" thing. Especially in a business environment, writing a new email takes more space than only a few words....

**Comment by leggett** [comment]
I was actually the one who came up with the design while working on Google Inbox. The Gmail design lead (who reported to me) liked it and adopted it for Gmail. 

Before that, compose was a [full-screen take over](https://www.webdevelopersnotes.com/tips/gmail/gmail-email-composition-window.jpg). 

Two problems with this: 

1. A full screen _encourages_ writing long emails. It screams, "Email is for many paragraphs." This has a couple problems: Long emails mean everyone else has more to read. Something can almost always be said better in fewer words. As Blaise Pascal said, "I have only made this letter longer because I have not had the time to make it shorter." And personal communication tends to be much shorter but felt out of place in Gmail.
2. You can't reference anything else while you are composing. We saw people in user studies start a message, save and close it, search for and open a new message, find information, go back to drafts, open their message, add information they found, repeat. We hoped they would pop the compose into a browser new tab or open a new copy of Gmail in a new browser tab.

Around this time: 

- Facebook had launched their new version of Facebook Messenger which gave everyone an @facebook address and defaulted to small compose boxes (making email feel lighter weight for personal communication)
- And Yahoo added tabs to Yahoo Mail (making multitasking easier)

We saw good feedback with both and liked aspects of both.

But adding tabs was problematic for a number of reasons and wasn't going to happen. At the same time, Gmail had Chat moles (what we called the little windows that popped up in the bottom right corner). They were well loved and so I wondered if compose itself couldn't just be a large mole. It could expand or even be popped out with familiar windowing controls for longer messages while making shorter messages feel more appropriate and even encouraged. 

This was back in 2008-2009. It wasn't too common to see a monitor larger than 24 inches and they didn't typically have the super high resolution today's monitors have. It blows my mind that some people have high resolution monitors and have their browser maximized across the entire screen. 

While the design is not perfect (looking in the bottom right of a screen to compose something isn't the best), I still hold it is better than a full-screen take over as the default experience. Every once in a while, I switch to full-screen as the default and enjoy the focused, slightly larger (but not overly so thanks to Simplify) experience. But it never lasts more than a few days and I return to the moles so I can multitask.

**Comment by erikgeurts** [comment]
I did not mean to offend anyone, let alone you personally. I agree that shorter emails are better than longer emails. However, your lengthy response above is the perfect proof that sometimes, a long message is necessary or even crucial. In a business setting, you can't really get away sending 7 word messages.

The way the semi-full screen version works nowadays is perfect for multi-tasking and for searching for information in the archive while keeping the draft open yet minimized in the corner, and then focusing on the message again without distractions.

In fact, I would argue that the tiny mole for composing a new message can also be very distracting because the entire rest of the inbox or folder is still visible.

**Comment by leggett** [comment]
No offense at all! It wasn't meant to be a defensive reply... I was just giving you the backstory.

Interestingly, your reply fit perfectly in the default mole: 😛 
<img width="646" alt="Screen Shot 2021-07-29 at 7 44 01 AM" src="https://user-images.githubusercontent.com/8763662/127512831-088abe4e-587c-46c4-8759-5e14c3329d6a.png">

I agree longer emails are sometimes unavoidable / needed. But that is the key: sometimes. That's why the compose is a mole by default and can be maximized. For those that mostly write long emails or prefer the maximized compose, you can elect to have that be the default.
