### ISSUE TITLE
Map space bar to selecting messages?

### ISSUE THREAD

**Issue by bluet** [leggett/simplify#603]
Something really, really useful to enhance daily workflow

- [ ] Using space to select (checkbox) mails .
  - On mail listing page, user already can use arrow key to move selection bar, but unable to select mail for further operations.
- [ ] Using [Del] and [Delete] key to ARCHIVE current mail or selected mails.
  - The [BACKSPACE] key could be touched accidentally while typing | or = or people think they are writing article.
- [ ] Customize-able key behavior.
  -  On settings page, after enable/disable switch, a button is present. After clicking the button, it captures key event to set the custom key.

---
System: Mozilla/5.0 (X11

**Comment by leggett** [comment]
On the `Space` key to select:
- I am hesitant to map space to something else as (a) it traditionally scrolls the page and (b) wouldn't be that obvious or discoverable. But I will consider it. 
- I do want to add shift+up/down to select multiple
- I already have an option to auto-select messages but it is off by default due to the risk you spelled out under your delete button suggestion.

On the `Delete` key to archive:
- More people delete than archive (surprising, I know)
- Archive already has a one-key shortcut (`e`), Delete does not
- I don't think having the delete key archive is intuitive. The key says delete, it should delete, no?
- Keyboard shortcuts do not work if you have focus in any text area, input, or content editable div (e.g. compose). People could always *think* they have focus in one of those and start typing but that is only a problem if you have a message selected or open. Still, it could be a problem which is why I have a setting to turn it off.

Customizable keyboard shortcuts:
- I do have hopes to let people customize the Simplify keyboard shortcuts. 
- Capturing the new shortcut is the easy part. The challenge is in how I store settings -- in localStorage. This does not sync between devices and can be erased when clearing browser data. That would be really bad for keyboard shortcut mappings so I want to fix that first.
- As for customizing Gmail's shortcuts, they actually let you do that under Gmail Settings > Advanced > Custom keyboard shortcuts. This will add a tab to Gmail's settings. But you can't use modifiers or system keys (Tab, Enter, Delete, arrows, etc).

**Comment by leggett** [comment]
As of v2.5.1, spacebar now selects messages. I also added support for Shift+Up/Down to select multiple messages. And don't forget I have auto-select as an option so you don't have to select at all!
