### ISSUE TITLE
Add extension configuration - enhancement

### ISSUE THREAD

**Issue by mightymouse2045** [leggett/simplify#62]
Hi there,

I am loving the interface - as you can see I have made a couple of changes:
- removed the split view and input icons
- Display nav icons when the menu is minimised

I'd love an enhancement to support options configurable in the extension settings for example?

- Display nav icons when minimised
- Show/Hide input options
- Show/Hide split view options
- Show/Hide Search
etc

I haven't done this 100% correctly and there are some unwanted side effects with the nav icons when hovering over the compose button and the background is not transparent when I hover over them for example. 

Also so I don't have to constantly hack these back in as you release new versions :p

![image](https://user-images.githubusercontent.com/878160/56259429-94c24080-6105-11e9-9cc3-9401cb35e534.png)

When no add-on is select I can't work out how to reduce the padding as per below image:

![image](https://user-images.githubusercontent.com/878160/56260028-04392f80-6108-11e9-9422-1a8499ea5617.png)

Next image shows the background on the nav menu I mentioned when hovering and still big gaps:

![image](https://user-images.githubusercontent.com/878160/56260212-f3d58480-6108-11e9-8a80-918709645d97.png)

**Comment by leggett** [comment]
I don't want to add settings as (a) it makes supporting the extension a lot harder (I have to test the intersection of each combination of settings with each of the various Gmail setups) and (b) it is against the idea behind the extension, an opinionated redesign of Gmail that doesn't try to make everyone happy. And my opinion on the nav being visible/accessible when minimized is I hate it. Passionately. So no desire to support that officially.

That said, I fully support people layering on top their own modifications as you're doing. Or you can download and modify the extension. Changes and updates are starting to slow down as I've worked through supporting all the Gmail configs and worked out most of the bigger bugs.

A few tips to try and help you:

- I think the margin you can't get rid of when the add-ons chooser is closed comes from the max-width on the main div. There are also some @media declarations to bump those max-widths for larger resolution screens.

- Where did the action bar go? Is it just super dimmed until you hover? 

- The background on the nav is likely important as in vanilla Gmail, the nav goes on top of the main view on hover instead of pushing the content over. It is weird that it is black though as you clearly have what I call a lightTheme (inbox items are on white bg, not black). So you'll have to override some of those colors.

- Showing search already has a setting sort of. It is sticky. If you open it and leave it open, it should stay open even after a refresh. This is easy to support as I already had to support search being open or closed.

**Comment by mightymouse2045** [comment]
Awww that sucks :P Ok well I'll just have to keep hacking.

Cheers :)
