### ISSUE TITLE
Display issue when mouse hover list (reading pane view)

### ISSUE THREAD

**Issue by DavidSpire** [leggett/simplify#640]
![image](https://user-images.githubusercontent.com/95707495/145816045-a1de8eaf-f4ef-4f55-9d33-b7aba18b9fce.png)
Current result: when you mouse hover the list (in reading pane view), then, when the 4 pictos for Archive, Delete, Snooze... are displayed, there is something that pushed message title and sample of content down.
---
Simplify v.3.0.3 - Configuration: aAX addOnsOpen appMenuOpen bundleInbox ca6 caC caD caI caL caS cfC cfO cfQ cfR cfU dateGroup defaultTheme fontMsg hideListCount hideMailTitle hideMsgCount inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthMd lowDensity minimizeChat msgLabelsRight msgOpen msgWidthFull navOpen newUI reverseMsgs rightStar showAvatars showChat simplify simplifyMenuOpen supExtWarn vPane - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 - Window: 1536 x 824 (100pct zoom) - Language: en

**Comment by leggett** [comment]
Thanks for the report. This is due to my not moving Personal Level Indicators (PLIs). Its on my list to fix.

I expect this goes away if you disable PLIs (only do that if you don't use them). That is the chevrons before the name that tells you if the thread is to only you or not. You can turn them off under Gmail Settings > General.

**Comment by DavidSpire** [comment]
Thanks for the feedback Mickael, it worked well by deactivating the PLIs!

**Comment by leggett** [comment]
I've got this fixed in v3.0.5
