### ISSUE TITLE
User avatars differ in size and padding between inbox and thread view

### ISSUE THREAD

**Issue by jaredzimmerman** [leggett/simplify#648]
![Screenshot 2022-01-08 2 06 41 PM](https://user-images.githubusercontent.com/430427/148661595-bc57110d-e4e5-45f6-811b-fefb6d0d7a49.png)

**Comment by leggett** [comment]
Thanks, the difference is largely intentional but looks bad in the inbox when you use a theme. As such, I plan to nudge them over in the next update.

- The size in conversation view is actually *small* for my taste and is on my list of things to play with
- The size in the inbox is based on the line height in the inbox
- The position in the inbox is set to align with the select all checkbox above – but it looks bad when you use a theme (they are way too close to the left edge of the list). I plan to move them over some in the next update.

**Comment by leggett** [comment]
One more thing, the default widths of the list and conversation view are different such that you can't tell they aren't in the same place. Just that there is a different left padding with the edge of the card/list.

**Comment by jaredzimmerman** [comment]
I use medium 960 for both, so its quite visible.

**Comment by leggett** [comment]
Setting both to 960px, I think this amount of padding looks pretty good:
https://user-images.githubusercontent.com/8763662/148664310-0e72a027-9dbd-4bad-bb42-eb0f5251f5ce.mp4

**Comment by jaredzimmerman** [comment]
The inbox view padding looks much better, the avatar sizes are really close now, but curious is there is any value of actually having them different in the two views, or finding a happy medium between the two to increase the feel of visual stability between the views (both in the avatar size as well as general alignment and margins within the app) e.g. why is the message body margin what it is?

**Comment by jaredzimmerman** [comment]
![Screenshot 2022-01-08 6 23 27 PM](https://user-images.githubusercontent.com/430427/148666703-1555889a-765b-4988-8ea9-bc8704a452a4.png)

**Comment by jaredzimmerman** [comment]
e.g. 80pt (or 90pt) padding left and right, 200pt avatars

**Comment by leggett** [comment]
**Yes, I believe there is value in the avatars being different sizes in the different views.** I'd like them to be more different (larger in conversation view) but making them bigger involves a lot of moving parts so I haven't done it yet. 

But, I've got a strong bias here. And I haven't tried them being the same size. Maybe consistency does look good here? So I tried it. Don't like it. Screenshots below. 

But first, to your question, what is the value in them being different between views?

- **In conversation view**, the avatars are 40px. I'd actually like them to be bigger at some point. A larger avatar doesn't the complete with the content near as much in this view. The content is much bigger (usually paragraphs and/or rich content for each avatar). 
- **In list view, the avatars** are 34px right now. I'd make them 32px (I try to stick to an 8px grid) but there is a bad flickering when I do that because of difference in the size of the checkbox element and the avatar. Making them 40px to match conversation view looks cramped and competes with the content too much in my opinion. It looks even worse if you don't opt to have the stars on the right of the list (the avatar dwarfs the star icon). 

This doesn't look good:
![image](https://user-images.githubusercontent.com/8763662/148671259-0bd08891-4bf4-4936-932d-d4701aefc40f.png)

It looks a tiny bit better with a theme (as the strong visual of the background prevents the avatars from being quite so bold) but they still just look oversized to me:
![image](https://user-images.githubusercontent.com/8763662/148671295-8236a497-808d-4a0f-a5bd-39067aaeef25.png)

**Comment by jaredzimmerman** [comment]
I don't see any issues with the sizing and spacing on the first option. then again I tend to prefer a wider line-height with more whitespace which would allow for the larger avatars. Having a larger line-height would allow you to do some interesting things related to showing some alternate lockups in multi-person threads showing stacked or split avatars as well. I think having the same width on inbox and thread view also sets up some expectation that the same base grid would be used across both (Google products are generally bad at this, not Simplify specific)
