### ISSUE TITLE
Tab + Enter clears recipients instead of sending the email

### ISSUE THREAD

**Issue by freb** [leggett/simplify#661]
I seem to recall that in previous versions of Gmail the "shortcut" to send email was `tab` followed by `Enter`. Looking at the shortcuts now, it looks like you are supposed to use `Ctrl + Enter` to send email. But in Gmail without this extension, `Tab` followed by `Enter` still works.

In Simplify, using `Tab` followed by `Enter` clears all but one of the recipients. I cannot tell what is selected when tab is hit, but it seems to have the effect of switching from "reply all" to just "reply". I'm not sure when this change was made, but it seems like only recently I've had issues with missing recipients.

It seems like hitting Tab from the message body should move down to send like standard Gmail does, and not up to an invisible entry in the reply drop-down menu.

Anyway, thanks for the great product!

---
Simplify v.2.5.12 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions dateGroup fontMsg grayTheme hideLabelChips hideListCount hideMsgCount hideTabIcons highDensity inInbox inList invertAddons invertCompose izBgDefault lightTheme listWidthLg minimizeChat msgWidthSm newUI simplify supExtWarn - System: Mozilla/5.0 (X11 Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4878.0 Safari/537.36 - Window: 794 x 943 (100pct zoom) - Language: en

**Comment by freb** [comment]
Trying to reproduce this, it looks like it does not do it on all emails. Though I cannot figure out what is different about the emails it does do it on. Maybe 50% of email threads are affected. As far as I can tell, it does not have to be an email with multiple recipients in have tab take you to the reply menu.

**Comment by leggett** [comment]
Figured it out. Will need to think about how to fix this, but there is a work around for now (below). 

**What is happening:**

- Simplify doesn't actually receive any key presses when the message body is focused, so I was really stumped on this one initially.
- Simplify does allow you to suppress the external recipient warning
- The close button on that warning gets focus before the send button when it is there
- But because the warning is hidden by Simplify, focus does not go to the send button next, it bubbles up to the body of the page (keep hitting tab and eventually you will see the search input gets focus)
- So I need to do more than hide the external recipient warning, I need to not let you tab to the close button so that tab always puts focus on the Send button. 


**Work arounds for now**: 

1) Use Ctrl+Enter to send mail (this will always work even if the external recipient warning isn't there) OR

2) Disable Simplify's suppression of the external recipient warning:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/8763662/154355020-35a4c80a-baaa-4ac8-9ae1-d92cc8a7563b.png">


**Bonus info: plans around the tab button and compose**
I have plans to add support for Tab actually indenting / unindenting content (or maybe just bullets). Not sure if it will be on by default or not... probably not but it depends on how I build it and how good I think it is when I do.

**Comment by leggett** [comment]
P.S. The reason it only happens sometimes is because the external recipient warning isn't always there.

**Comment by freb** [comment]
Thanks for the workaround. I've disabled suppression for now.

**Comment by leggett** [comment]
I went ahead and figured out a fix for this which is to detect the banner, wait, and then simulate a click on the close button in the banner. Pushing out with v2.5.13... Edge and Safari will take a while but Chrome and Firefox should be updated within 24 hours.

**Comment by leggett** [comment]
P.S. I only close the banner when you have Simplify set to hide the banner.
