### ISSUE TITLE
Bundles jump around (upon email delete/archive) when there's a wide range of dates in the bundle-emails

### ISSUE THREAD

**Issue by louthy** [leggett/simplify#690]
When a bundle is open, if there are several items from different dates, then deleting the top item could cause the bundle to re-order itself within the inbox, causing the bundle to jump.  It means that we always have to be a little bit tentative working through the bundle archiving/deleting - which obviously isn't ideal, it means I'm not entirely confident the next item will be where it is now post-action.

I am assuming the bundle box has some live state that the renderer uses to know it's open?  I wonder if the bundle itself could be tagged with the date & time of the first item in the bundle (upon opening), and then be sorted in the view with that date & time, rather than the current _first-item-in-the-bundle_ (which I assume is how it's being sorted now)?

---
Simplify v.3.0.20 - Configuration: aAX bundleInbox ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup fontList fontMsg hideEmoji hideLabelChips hideListCount hideMsgCount hideSelectRefresh hideTabIcons inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity mediumTheme minimizeChat msgLabelsRight msgWidthLg newUI reverseMsgs rightStar showAvatars simplify simplifyCanary supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 - Window: 1645 x 1103 (101pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Yes, this is on my list. I'll take this opportunity to try and figure out how I'll fix it. 

**First, a couple work arounds you can use now:** 
1. You can change Simplify's settings to open the bundle instead of expanding it. This has the co-benefits of the bundle not moving and you get to see all the emails in the bundle instead of just the emails on the current page. 

Achieve this by turning off this setting: <img width="689" alt="image" src="https://user-images.githubusercontent.com/8763662/173847414-a18d7dee-5327-44b2-b455-9afbde5b2d21.png">

2. You can be careful in how you process mail in a bundle. I like to read what I'm going to read, star what I want to keep in the inbox, and then click the "Archive unstarred" action on the bundle (in the bundle title bar) to sweep the unstarred items.


**The key question is: if I keep the bundle in the same position, when do I put it in the correct position?** 

1. I could do it when you close the bundle - that's jarring and probably bad if focus stay on the bundle
2. I could do it a random amount of time (30 seconds? 2 minutes?) after the bundle is closed and de-focused - I find that any answer to this feels random (though that still might be better than the current experience)
3. I could do it the next time Gmail updates the list - that feels random unless the user clicked the refresh list button

Probably some combination of (2) and (3) where I never update if the bundle wasn't closed and defocused and then I update it after N seconds or if the user clicks refresh. 

**How do I technically keep the bundle in that place?** (This is more notes for myself / me thinking out loud) 

Keeping the bundle in the same position when the first item is removed is generally hard because of how Gmail works and how I've built bundling (it is heavily dependent on the position of the newest item in the bundle).

Background on Gmail: Gmail deletes and recreates the DOM for the entire list when anything new comes in, the list is refreshed, or anything is removed. Simplify keeps track of the state of the list outside the list and then recreating that state every time the list is recreated by reselecting, regrouping, rebundling, and restoring the bundle state, focus, and scroll position. When you remove an item, I also have to correct what gets focus next according to the order/grouping you saw (otherwise Gmail would have moved focus to what was next in the order it assumes the list is in). 

Background on Simplify bundling: Simplify basis the bundle position on the newest item in the bundle. I give every item in the inbox (emails and bundle titles) an order value. Every message has a default value that increments by 100's. When something is bundled, I update those values in increments of 1's so all the bundled threads are before the next item and place the bundle title at the original position of the first thread (always an increment of 100).

Technical options: 

1. I can cache the order value but it will conflict with a new message that likely isn't in the bundle as the entire list was rebuild and rebundled. Maybe I can check the cached order value and skip it when bundling. 
2. I can reserve a place for a cached bundle in my counting (maybe xx99). That might break things that generally assume a bundle to always be at xx00. Maybe all bundle titles need to be at xx99 all the time? 

I think I'll start with (1) as it involves less refactoring. I worry it might break when there are double bundles (a thread in multiple labels which puts multiple bundles in a row and in the same order).

**Comment by leggett** [comment]
Ok, I've been working on this for the last couple weeks and I finally had a breakthrough this morning. More to button up but I should get this out in the next update (v3.0.22).

**Comment by leggett** [comment]
Ok, took care of a bunch of edge cases and this is rolling out with v3.0.22. Thanks for the report. Sometimes the squeaky wheel gets the grease. While it was on my list, I was avoiding it some because I knew it was going to be a beast to get working.

**Comment by louthy** [comment]
Perfect, thank you!  It's sooo much better.  And thanks for fixing https://github.com/leggett/simplify/issues/691 too 👍
