### ISSUE TITLE
When there's only a single item left in the bundle, it collapses into a single email

### ISSUE THREAD

**Issue by louthy** [leggett/simplify#691]
When there's only a single item left in the bundle, it collapses into a single email.  This feels like quite a jolt and can sometimes take a bit of time to find the last email in the bundle I'm working through.  Would it be possible to maintain an open bundle for as long as there are emails remaining, or until we manually close it?  

Related: https://github.com/leggett/simplify/issues/690

---
Simplify v.3.0.20 - Configuration: aAX bundleInbox ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup fontList fontMsg hideEmoji hideLabelChips hideListCount hideMsgCount hideSelectRefresh hideTabIcons inInbox inList invertAddons invertCompose izBgDefault listWidthLg lowDensity mediumTheme minimizeChat msgLabelsRight msgWidthLg newUI reverseMsgs rightStar showAvatars simplify simplifyCanary supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 - Window: 1645 x 1103 (101pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Thanks for the report. I'm conflicted about this one – it makes sense when you are clearing out a bundle but it is annoying on the other end where you got a single email and instead of showing it, it is obfuscated behind a bundle. I haven't developed the capacity to do something different between initial bundling on receipt and bundling as you are clearing things out.

That said, there is an option in Simplify settings to bundle even if there is only one email. It is off by default right now and I aim to figure all this out before I launch out of beta.

**Comment by leggett** [comment]
Ok, I got this one fixed too. Rolling out in v3.0.22. 

There remains an option (on by default) to only bundle when there is more than one message in a label or category. BUT, if you are cleaning out a bundle, it will stay in a bundle even when there is only one message left. If you close the bundle with only one message left, it will unbundle and go to the correct location in the list based on the timestamp on the thread.
