### ISSUE TITLE
Change inbox view font to Helvetica Neue

### ISSUE THREAD

**Issue by melissachang** [leggett/simplify#71]
I much prefer Inbox's font. I find it much more relaxing and modern. Maybe it's because I subconsciously associate it with Inbox. Roboto looks like 1990's era Arial to me.

If you want to try it out, put in `style.css`:
```
* {
  font-family: Helvetica Neue, Helvetica, Roboto, RobotoDraft, Arial, sans-serif !important;
}
```
WDYT?

**Comment by leggett** [comment]
I like Helvetica Neue better than Arial. BUT, not everything is in Arial. 

The subjects are in Google Sans (which I really like) and things like code is in a mono-spaced font. This would also override any html emails or font choices made in Gmail itself. 

I could apply this without the !important but then it gets unevenly applied and things start not being aligned correctly. So I'm not going to mess with the font-family. 

I am, however, playing with the font size.

**Comment by melissachang** [comment]
FYI - I've been using the above css for a couple days. Email font (in email view) is not overridden.

**Comment by leggett** [comment]
It changed the subject and the monospaced font for <code> blocks for me. Are you seeing something different?

BEFORE:
<img width="978" alt="Screen Shot 2019-04-23 at 10 55 38 AM" src="https://user-images.githubusercontent.com/8763662/56604341-95038580-65b6-11e9-86f8-3238ca9857ab.png">

AFTER:
<img width="961" alt="Screen Shot 2019-04-23 at 10 56 30 AM" src="https://user-images.githubusercontent.com/8763662/56604360-9a60d000-65b6-11e9-97a9-e448a731c582.png">

**Comment by melissachang** [comment]
Sorry you're right, never mind

**Comment by melissachang** [comment]
Sorry I wasn't clear in the initial PR. I'm mainly interested in the inbox view (not email view), specifically the email recipients and subject:

![Screen Shot 2019-04-23 at 10 23 52 PM](https://user-images.githubusercontent.com/10929390/56634413-cd3ab080-6616-11e9-9722-13fc87a05b41.png)

Currently those are Roboto. Would you be open to only changing those to Helvetica Neue?

(In Inbox, those stood out to me as being Helvetica Neue. I don't remember anything from email view standing out to me.)

**Comment by leggett** [comment]
Ah.. I could change the inbox font. Will look into it soon.

**Comment by yurikhan** [comment]
I feel strongly against this, for many reasons.

The easy-to-explain, surface reason is that Helvetica Neue, if installed on the user’s system or allowed to be downloaded, has no coverage beyond Latin. This means that a user who is likely to receive mail in English and Russian — such as me — or English and Greek, or English and something else — will see subjects of some messages in Helvetica Neue and subjects of other messages in whatever font it falls back to.

Speaking about fallback: In the styles as written, the first fallback font is Helvetica. On Fontconfig/X11/GNU/Linux, it maps to Nimbus Sans L, a Type1 font that has atrocious kerning for Cyrillics.

The deeper philosophical reason is that Gmail is an application, and an always-running application at that. As such, it really ought to use the same fonts as the rest of the user’s system. For example, on my system, it would be Ubuntu Light for UI text, Arimo for proportional content text, and Cousine for monospace content text. Other users have different preferences, and Gmail ought to accommodate them, too.

(Yes, I realize that CSS does not really have a way for a page to say, “hey, I’m an application rather than a web site, so please use the theme fonts and colors”. Just frustrated about it.)

Does each user really have to fork this extension to hardcode his/her preferred fonts?

**Comment by leggett** [comment]
Thanks Yuri. I ended up not making this change for various reasons. 

I'm also not going to force it to use the another font. Instead of forking it, I recommend you build a super simple extension that sets the font and runs along side Simplify. Then you don't have to maintain the core updates.
