### ISSUE TITLE
Emojis in compose window are inverted in color when using dark mode

### ISSUE THREAD

**Issue by rcdailey** [leggett/simplify#717]
When using dark mode for the compose window, emojis are inverted in color. See the screenshot below.
![image](https://user-images.githubusercontent.com/1768054/186426503-e1e7e4b5-dd7c-49b3-9554-76ec5b9ef0d2.png)

**Steps to reproduce:**

- Open a compose window with dark mode enabled
- Press `WINKEY + .` to open the Windows emoji search & insertion tool. Pick the smiley face and enter it.
- Notice the color of the emoji is inverted.

**Expected behavior:**

In dark mode, emojis should not have their colors inverted.

---
Simplify v.2.5.25 - Configuration: aAX addOnsOpen appNavOff ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab darkTheme dateGroup fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inLabel inList invertAddons invertCompose izBgDefault listWidthLg lowDensity minimizeChat msgWidthSm nPane navOpen newUI openMole reverseMsgs simplify supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63 - Window: 1591 x 1390 (101pct zoom) - Language: en

**Comment by leggett** [comment]
Hi Robert. Thanks for this report. Can you email me at hi@simpl.fyi with an emoji inserted this way? Windows must insert them differently than Mac or the Gmail emoji picker.

**Comment by rcdailey** [comment]
Done!

**Comment by leggett** [comment]
Unfortunately, I don't think I can do anything about this. Emoji inserted with the system picker (on Windows and Mac) insert a glyph that I can't un-invert. If you use Gmail's inferior emoji picker, it inserts an image that I can un-invert. 

The good news:

1. What you see is not what you send. The emoji will not look strange to the recipient.
2. I have started revamping dark mode and may consider either better compatibility with Dark Reader or incorporating their functionality (they open source their extension) which checks every element and figures out how to manually set the color so it is inverted instead of trying to strategically use css filters (what I do).

**Comment by rcdailey** [comment]
Sounds great. Thank you for spending time on this. I'll go ahead and close.
