### ISSUE TITLE
Keyboard shortcuts sometimes still active during search

### ISSUE THREAD

**Issue by mgalgs** [leggett/simplify#719]
Sometimes, while entering text into the search bar, if I press a key that's assigned as a hotkey for a keyboard shortcut (e.g. "x" for select or "e" for archive) the shortcut action is executed, even though it should be inhibited while typing in the search bar. The result is the execution of a bunch of unintended (possibly destructive) actions while typing a search term.

This doesn't happen all the time. It seems like toggling Simplify on/off seems to fix it for a while.

Repro:

1. Focus the search bar
2. Type "tax". Note that when the "x" is typed the selection status of the currently focused conversation in the list is toggled.

---
Simplify v.2.5.25 - Configuration: aAX ca3 caI caL cfC cfO cfQ cfR cfU composeActions composeFab dateGroup defaultTheme fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons inList inSearch invertAddons invertCompose izBg2 lightTheme listWidthLg lowDensity matYou minimizeChat msgWidthSm newNav newUI simplify supExtWarn - System: Mozilla/5.0 (X11 Linux x86_64 rv:103.0) Gecko/20100101 Firefox/103.0 - Window: 1920 x 1080 (119pct zoom) - Language: en

**Comment by leggett** [comment]
Yikes! A few thoughts:

- First off, you should disable "Auto select" in Simplify's settings if you haven't already (last option in the keyboard shortcuts section). If you want to go even further, you might turn off Gmail's keyboard shortcuts but that seems a bit extreme.
- I can't reproduce this and haven't gotten any other reports. 
- I do a lot of things to make sure this never happens (it shouldn't happen if focus is in ANY input or editable field of any kind).
- That said, I take this kind of issue very seriously (because it is serious). Maybe it is something about your set up... maybe another extension is conflicting... maybe you're in a Gmail percent experiment. Maybe a lot of things. 

**Next step to help me troubleshoot:** Would you be willing to send me a video (here or email to hi@simpl.fyi) of this happening with Simplify's debug mode turned on (last option in Simplify options) and the browser console open (Tools → Browser tools → Browser console)? Like this:

https://user-images.githubusercontent.com/8763662/186489226-f72956e1-2986-43fe-bef8-e93cf24bc156.mp4

**Comment by leggett** [comment]
Also helpful to hear of any other extensions you use to modify Gmail (if any)

**Comment by mgalgs** [comment]
I don't have any other extensions to modify Gmail. I'll get a video+debug the next time it happens. Thanks!

**Comment by mgalgs** [comment]
Well shoot, it just happened again but after I turned on debug and pulled up the console I could no longer reproduce the issue... Heisenbug :cry: 

It seems like it only happens when starting a new work session, before my gmail tab is fully "warmed up" :sweat_smile: Today, for example, I had just woken my computer from sleep, went to my gmail tab (which I always leave open), and started a search with the `/` shortcut straightaway. It *seems* like I only see the issue if I jump straight in to searching (via `/`) without first clicking around on conversations.

**Comment by leggett** [comment]
Very helpful -- it might be something (Gmail, Simplify or both) aren't fully initialized for some reason. Or that focus is somehow moved out of the search box right after you moved it into it. 

I'll try to reproduce this on my end with the ` / ` shortcut.

**Comment by mgalgs** [comment]
Hey @leggett, I just encountered this issue again and have been able to reproduce it fairly consistently with the following steps:

- From the main inbox view, click on a conversation with the mouse.
- While in the conversation view, hit `/` to focus the search bar.
- Start typing (seems like you need to start typing fairly quickly after hitting `/`). You should see your search input being interpreted as keyboard shortcuts.

HOWEVER!!!

I'm still able to repro the issue with Simplify disabled :sob: So the good news is that it doesn't seem to be related to Simplify, the bad news is that I'm back to the drawing board for getting it fixed (I have little hope that submitting a bug report to gmail will go anywhere).

Thanks again for your excellent extension (each time I disable it and my eyes start bleeding I'm reminded how much I love it) and I apologize for the noise here since this ultimately wasn't a Simplify issue.

Edit: I've submitted feedback to Google. Will update this issue for any wary travelers who land here in the future.

**Comment by leggett** [comment]
Interesting. I can reproduce that on my end but I have to press the key immediately after pressing "/" (sub-second delay). Even then I can't always get it to happen. 

And to confirm, Simplify checks if focus is in any kind of editing state (an input, email, subject, etc) and doesn't do anything if it is.

My guess is the issue is a performance issue where Gmail isn't realizing that focus is in the search box immediately after pressing "/". Things you can do to speed up Gmail:

- Enable Gmail's offline mode (you can only enable it for one account per Chrome profile)
- Use fewer add-ons / extensions on Gmail (no extension can speed up Gmail's performance... I've done a lot of work to minimize Simplify's impact I haven't heard any complaints in a long time but maybe?)
- Refresh the Gmail tab every so often (like every few days? it might also be more impactful to close the tab and open Gmail in a new tab as I think the tab's memory footprint isn't really flushed on a refresh)

**Comment by mgalgs** [comment]
Yeah could be some kind of performance sensitive race... I'll try your suggestions, thanks!
