### ISSUE TITLE
Tab navigation shortcuts

### ISSUE THREAD

**Issue by larmarange** [leggett/simplify#728]
Hi, I have been searching for a way to navigate between tabs (inbox, forum, promotions etc.) using my keyboard, but I didn't find any shortcut, in the documentation or the ? page. Maybe I have missed it. If not, it could be relevant to introduce dedicated shortcuts.

**Comment by leggett** [comment]
Gmail has a shortcut already: the [ ` ] key.

**Comment by larmarange** [comment]
Thank you for your feedback.

Of course, these are characters not available on non English keyboards ;-)

**Comment by leggett** [comment]
You can change it!

Under Gmail's settings > Advanced > Enable "Custom keyboard shortcuts"

Then go back to Gmail settings > Keyboard shortcuts > Go to next inbox section and Go to previous inbox section. 

Simplify v3 (with bundles) depends on a lot of shortcuts being unchanged (esp around actions on messages). So I suggest you not change other shortcuts or know that if something isn't working in the future, it might be because of customizations here.
