### ISSUE TITLE
Adding hidden categories to inbox tab 

### ISSUE THREAD

**Issue by perks** [leggett/simplify#738]
Hey, just started using Simply and had a question concerning the old category labels you re-added - Is there any possibility to get these added as inbox tabs as well aside from just the left nav?

**Comment by leggett** [comment]
The short answer is not really. But the long answer is sort of if you'd be up for [trying bundles](https://www.fastcompany.com/90698042/simplify-gmail-inbox-bundles) instead of inbox tabs which is in the [Simplify v3 beta](https://beta.simpl.fyi/). [Short demo video here](https://www.youtube.com/watch?v=6WeIT0k2oY4).

Below is more background on the categories, Simplify, and how you can get bundling to work for the hidden categories:

**First, some background:**

- Simplify makes 3 additional categories (Finance, Purchases, and Travel) visible in Gmail's left navigation as links to a search for each category.
- These categories are from Google Inbox and are still applied to incoming email in the background but Gmail decided to hide them entirely in Gmail's interface. 
Instead of making them visible, Gmail decided all of the messages in these categories would show up in the "Updates" category. 
- It is not possible to show these extra categories as inbox tabs nor can you show the category label on threads.
- It is not easy to modify the email in these categories. (It is actually impossible but there is a work around I'll get to shortly)
- The limited functionality is why Simplify doesn't show them in the nav by default.

**A glimmer of hope:**

- There is a way to make these hidden categories into working labels...
- You can create your own label (I use "Orders" for category:purchases, "Finances" for category:finance, and "Trips" for category:travel) 
- Then create a filter for each category (e.g. enter "category:purchases" for "Has the words").
- Add the label you created AND change the category to "Primary" (otherwise it will be in your label and in the Updates category) -- _Note: this will not remove the Purchases or Travel category but for some reason, it does seem to permanently remove the Finance category with no way to add it back._ 
- Profit!
- Since this is a label, you can change what is in it and show the label in the list so email will bundle on it.
- The reason that works is that categories are always applied in the backend before any of the user filters are run. So while you can't filter based on labels, you can filter based on categories.
- I've been testing this for over a year and it is working flawlessly for me.
- But I will have to do some work to figure out how to automate setting all this up (as it involves creating labels and filters).

**Comment by perks** [comment]
Awesome thanks for the quick reply -- I'll definately check this out and looks useful!
