### ISSUE TITLE
Can't click on Grammarly using inline reply

### ISSUE THREAD

**Issue by SamEdwardes** [leggett/simplify#741]
I like to use Grammarly to edit my emails. Would it be possible to modify this view so that Grammarly is clickable?

![Screenshot 2023-03-17 at 08 56 24@2x](https://user-images.githubusercontent.com/18248949/225956066-a53f03a5-0dbd-4add-8f97-4a05b8fb0055.png)

For example, it works in pop-out replies:

![Screenshot 2023-03-17 at 08 58 44@2x](https://user-images.githubusercontent.com/18248949/225956396-87dc1982-8ba1-4d59-b01f-80dcb867183c.png)

**Comment by leggett** [comment]
Thanks for the report and the screenshots -- I'll look into it this weekend.

**Comment by leggett** [comment]
1. This is really a Grammarly bug in some cases (depends on window size and how you have Gmail set up) that Simplify makes more common (see below video)
2. Immediate fix: hide the formatting bar or use Simplify's option to only show a few formatting options (which puts them inline)
3. I'll see if I can find a permanent fix but it is hard because of how Grammarly injects itself into Gmail (with a shadow-root)

Video of the bug with Simplify on or off:
https://user-images.githubusercontent.com/8763662/226191479-1ed91448-7f9d-43b2-b403-42b9ac72a466.mp4


Occasionally, Grammarly will move itself up to avoid getting covered by the formatting options but (a) I can't figure out what triggers it to do that and (b) when it does this, it works fine with Simplify on too:
https://user-images.githubusercontent.com/8763662/226191873-d8a330a6-604d-43b3-ab71-5044409afdd9.mp4

**Comment by SamEdwardes** [comment]
The videos are not loading for me, but thank you for looking into! I know it may be outside if Simplifys scope or control. Just wanted to share in case it was an easy fix. Keep up the awesome work!

**Comment by leggett** [comment]
I figured out a bandaid where I move it up if the formatting bar is open. Sometimes this isn't needed and Grammarly is further up than the bottom right corner. But it will ensure it is above the formatting bar when it is an issue.

**Comment by leggett** [comment]
P.S. I'm shipping this in the [v3 beta channel](https://beta.simpl.fyi) first to make sure it doesn't break something.
