### ISSUE TITLE
"Saved Searches" feedback

### ISSUE THREAD

**Issue by leejoramo-d51** [leggett/simplify#776]
I love the new saved searches feature. What a great addition to bring at the end of the long Beta process. I have two minor things:

1. It took me insanely too long to figure out how to create my own saved searches. Yes, I read the instructions many times. But I kept looking in the "Show Search Options" dialog or for a button on the search results list page. I finally figured it out, and of course it makes sense, but it did trip me up. Probably if I had seen a demo video, I would have figured it out right away. (I am sure, you will be releasing a 3.1. video at release)

2. The first Saved Search I looked for was to show emails without Labels. I am not perfect at this, but I really try to make sure that all of my emails have labels automatically applied by Filters, or do so manually. I always have to refer to notes for this search that is a bit to complex too remember, and the search options dialog doesn't help. 

`has:nouserlabels -label:Inbox -label:Chats -label:drafts -label:trash`

I added it to my Searches, but I think this would be a good search to include.

**Comment by leggett** [comment]
Thanks for the feedback. Adding a "Add saved search" button to prefs would be easy. I can also add one at the bottom of the expanded list. That will go out in the next update

And thanks for the suggested search. Will consider...

**Comment by erikgeurts** [comment]
> `has:nouserlabels -label:Inbox -label:Chats -label:drafts -label:trash`

On a side note: your search for conversations that have no label looked very interesting, and I tried it just now.

I was a little bit surprised however, that it returned some conversations that do look like they have a label assigned.

My thinking is that this might be caused by (at least) one email in the conversation not having a label. The conversation as a whole is displayed in Gmail as having a label, but this search still surfaces individual emails that have no label, and thus their conversation. Is that plausible?

**Comment by leggett** [comment]
That is exactly it Erik. Gmail search is all message-based but the interface is thread-based. So search does unexpected things. I tried to get them to fix this when I was on Gmail but failed. :(

**Comment by leejoramo-d51** [comment]
Oh, yeah, I  normally take the additional step of unchecking `Quick Settings -> Email Threading -> Conversation View` when using this search.
