### ISSUE TITLE
When no conversations are selected, "Y" keyboard shortcut should archive focused conversation

### ISSUE THREAD

**Issue by andyszy** [leggett/simplify#78]
I loved speeding through Inbox with keyboard shortcuts.

With Gmail it feels like it takes twice as many keystrokes to archive a bunch of messages, because I need to hit "X" then "Y" to select and archive a message.

I'd love it if Simplify could bring back the Inbox behavior here. No idea how easy/impossible this is.

**Comment by leggett** [comment]
The way I would do that is always have the current item in focus selected. 

This has two downsides: 

1. Unlike Inbox where they had selected and focused, Gmail only has actions work when you have the item selected. So there would probably be no way to select via keyboard shortcut. You could only do it via mouse or one at a time.
2. It is risky with single key shortcuts. You might think compose or search or chat has focus and start typing not realizing you're moving messages around until it is too late. Maybe that's fine for Simplify users in the same way it was ok for Inbox (it is a self selecting user base).

I'll think on it some more.

**Comment by leggett** [comment]
Adding to the someday maybe list.

**Comment by leggett** [comment]
I spent some time on this and related things seeing if I can simulate a click or a keypress (to select the current item). So far no luck. I'm not sure if it is possible due to working in isolated worlds. 

**Here is some of the code I tried:**

To simulate a click:
`
document.querySelector("#elementId").click();

var evt = document.createEvent('MouseEvents')
evt.initMouseEvent('mousedown', true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
document.querySelectorAll('.tab-button')[0].dispatchEvent(evt)
`

To simulate a key press:
`
console.log('Trying to press "x"');
var pressthiskey = 'x'; /* <-- q for example */
var e = new Event('keydown');
e.key = pressthiskey;
e.keyCode = e.key.charCodeAt(0);
e.which = e.keyCode;
e.altKey = false;
e.ctrlKey = false;
e.shiftKey = false;
e.metaKey = false;
e.bubbles = true;
document.dispatchEvent(e);
`

I also started to play with using [Chrome's messaging system](https://developer.chrome.com/extensions/content_scripts#execution-environment)... maybe this is a better path?

`
var port = chrome.runtime.connect();

window.addEventListener(
  'message',
  function (event) {
    // We only accept messages from ourselves
    if (event.source != window) return;

    if (event.data.type && event.data.type == 'FROM_PAGE') {
      console.log('Content script received: ' + event.data.text);
      port.postMessage(event.data.text);
    }
  },
  false
);

setTimeout(function () {
  // Add event listener to menu button to tripper posting message
  document.querySelector('.gb_5c > .gb_vc').addEventListener(
    'click',
    function () {
      window.postMessage(
        { type: 'FROM_PAGE', text: 'Hello from the webpage!' },
        '*'
      );
    },
    false
  );
}, 5000);
`

**Comment by cy2k** [comment]
Man if you could figure this one out it would be killer...  
It does seem like a tricky one, though. Maybe our time would be better spent figuring out if anyone that uses Simplify knows anyone that works on Gmail and trying to get them to do it on their side!  haha

**Comment by leggett** [comment]
If I can figure this out, it dramatically opens up the things I can do with Simplify... so I want to see if I can figure it out.

Another possible reference:
https://cdn.rawgit.com/ccampbell/mousetrap/2e5c2a8adbe80a89050aaf4e02c45f02f1cc12d4/tests/libs/key-event.js

**Comment by leggett** [comment]
I now have this working in Simplify Gmail v2. 🥳 

I'm currently only doing it for the following actions:

- Archive
- Mark as spam
- Delete
- Mark as unread
- Mark as read
- Snooze
- Add as task
- Move to
- Label as

I suspect there are ways I can make this a little better for edge cases. Like, if you press [v] to move a message and then change your mind (pressing [esc]), I should probably unselect the thread. 

It is a bit complicated to know the difference between that and selecting the thread > pressing [v] > hitting [esc] -- in this case I shouldn't unselect the message. So I'll probably ship this as is as an opt-in feature initially and see what the feedback is.
