### ISSUE TITLE
Emails on different pages of inbox aren't bundled together

### ISSUE THREAD

**Issue by scrooop** [leggett/simplify#815]
I've been creating a bunch of filters that create labels and therefore group emails together in bundles, and I noticed that if there are, say, 10 emails that fit the criteria of the filter and are therefore marked with the same label, and 5 of them are on page 1 of your inbox, and the other 5 are on page 2 of your inbox, there's one bundle on page 1 that contains the first 5 emails, and then another bundle on page 2 that contain the second 5 emails. It would be nice if there was an option to bundle all emails together regardless of what page they're on.

---
Simplify v.3.1.9 configuration: aAX appNavOff avatarsZoom boldHighlight bundleInbox bundleLists caA caI caL cfC cfF cfO cfR cfU composeActions composeFab contrastTheme dateGroup fontList fontMsg fontNav gaArchive gaRemove groupHideFirst groupOtherLists hideAds hideEmptySections hideExtWarn hideFileIcons hideInboxHideAllLink hideLabelChips hideListCount hideMsgCount hideMsgReplies hideTabIcons highDensity importantBadge inInbox inList invertAddons invertCompose izBg23 lightTheme listWidthXLg maDone maPin matYou msgWidthMd navOpen newNav newUI quickSettings reminders rightImportance rightLabels rightStar sendLater simplify simplifyPrefsOpen- System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0 - gmail.pinto-server_20240502.06_p0 - Window: 1504 x 771 (101pct zoom) - Language: en - Errors: / 1918:71: get(.dC .hG) called with undefined parent, null / 12726:36: Uncaught TypeError: get(...).addEventListener is not a function

**Comment by leggett** [comment]
I would love for this to be the case, but it is not possible given the limited access I have (e.g., without full API access, I can only see what is on the screen). 

You can change Simplify to open a bundle as a search instead of expanding inline with this preference:
https://mail.google.com/mail/?simplify=bundles&pref=bundleExpand

But there are some downsides to this if you do this. The main one is some emails may not appear in the search I navigate to due to flaws that have always existed in Gmail search. I explain it in this video:
https://www.youtube.com/embed/CPTcZKcFtMA?autoplay=1&rel=0&showinfo=0&vq=hd1080&start=72

**Comment by leggett** [comment]
I'll add, you can keep bundles expanding inline and still open the search from the inbox with ⇧O or the "View all in ____" in the bundle's menu:
<img width="266" alt="image" src="https://github.com/leggett/simplify/assets/8763662/6e66b7ea-06ab-476e-91df-525bf6d52d5d">

I've thought about making this more obvious with a visible "View all" button at an expanded bundle.
