### ISSUE TITLE
Pressing arrow keys at the end of a paragraph jumps the cursor to the "show trimmed content" indicator.

### ISSUE THREAD

**Issue by jwpalmer** [leggett/simplify#834]
In Safari, when typing an email reply, pressing right or down arrow keys at the end of any paragraph removes the cursor and jumps focus to highlight the "show trimmed content" indicator at the bottom of the email. 

This is super annoying, especially since there's no longer an active cursor, so keyboard shortcuts now apply. Further accidental keystrokes will potentially delete the trimmed content, exit the email, archive, head back to the inbox, etc. Very disorienting.

**Comment by leggett** [comment]
This is unfortunately a Gmail bug in Safari.

I've got on my list to attempt to fix it as I've done with a few other Gmail bugs in Safari but I haven't gotten to it. But it is tricky because (a) it involves keystrokes while the composer is in focus (something I try to not get in the middle of) and (b) I don't want to prevent focus when it is intentional / supposed to happen. 

I'll add you to my list of people to notify if/when I fix it.

**Comment by jwpalmer** [comment]
Dang, sorry to hear that and for even putting this on Simplify in the first place! Very much appreciate your core principle of not getting into keystrokes in the composer. One more sad point for users in the browser wars.

If you do happen to snag a fix through some reasonable means I'd be grateful, but I do think I prefer that you're enhancing Gmail or correcting its usability flaws, rather than fixing bugs that Google should be handling anyway.

As an aside, also wanted to express my ongoing thanks for providing Simplify to us. I know it's a lot of work and probably comes with loads of weekly/daily annoyances, but I've yet to see anyone take on what you have. When you're ready to offer an entirely independent email client, I'll be the first to sign up.
