### ISSUE TITLE
Bundle has archive all button instead of archived unstarred button

### ISSUE THREAD

**Issue by hk2906** [leggett/simplify#835]
My workflow up until now has been to use Simplify with "Do not bundle starred conversations" disabled, and to go through my bundles, pin/star any emails I want to action, and use the archive unstarred/pinned button at the top to archive the rest.  This then keeps the actionable emails bundled basted on category for me to action.

Recently, the archive all button at the top of the bundle now archvies all emails, not just unstarred / unpinned.  I'm not quite sure what the purpose of pinning would be for anyone with the "Do not bundle starred conversations" setting disabled, if pinned conversations can be achived anyway.

**Comment by leggett** [comment]
Yes, I did change this recently and I should have expected it to break the workflow for some. I'm sorry it changed on you suddenly. :(

I changed because I got the opposite feedback from a few users: "I disabled the 'Do not bundle starred messages' and expect the archive all button to apply to all the messages in the bundle since that option is disabled."

I'd rather not have another option here... but maybe that will be needed. 

I probably should make the default the way it was before as more people probably are used to that and figure out a new option for the people that expect it to work the other way. 

Something like, "Apply bundle actions to unstarred/unpinned messages" = Off by default

**Comment by leggett** [comment]
v3.1.27 is rolling out to users over the next couple days. In this update, I reverted the default experience to what it was before and I added new options to change how it works (both what bundle actions are shown and what they act on):

<img width="431" alt="image" src="https://github.com/user-attachments/assets/37396370-d1d5-49e4-8d7a-b9c98befe23a">
