### ISSUE TITLE
Search glass overlaps with settings icon

### ISSUE THREAD

**Issue by biofool** [leggett/simplify#97]
<img width="470" alt="Screenshot 2019-04-26 11 29 16" src="https://user-images.githubusercontent.com/1031599/56833038-46f2ba00-6822-11e9-9d80-ebeb368aee89.png">

Clicking on the overlayed area results in getting the chrome settings menu.
Work around:
In settings enable keyboard shortcuts and use the / menu to get to the search input box or disable the boomerang plugin.

<img width="587" alt="Screenshot 2019-04-26 11 36 50" src="https://user-images.githubusercontent.com/1031599/56833150-828d8400-6822-11e9-9194-7eb5a85e49d1.png">

<img width="396" alt="Screenshot 2019-04-26 12 56 56" src="https://user-images.githubusercontent.com/1031599/56833248-d009f100-6822-11e9-9e21-184f1211127a.png">

**Comment by staringispolite** [comment]
Heh, was just going to log this one as well. It works great if you disable Boomerang, it's just that the UI doesn't adapt  

With Boomerang enabled:
![image](https://user-images.githubusercontent.com/151620/56839373-08b3c580-6837-11e9-8aa9-b4df5e2d37e6.png)

Without:
![image](https://user-images.githubusercontent.com/151620/56839385-1b2dff00-6837-11e9-9105-4d4b9a6007f8.png)

**Comment by staringispolite** [comment]
Playing with Chrome Inspector a bit, it looks like if you were to insert the search icon and form into the same 'menu bar'-type div that the other actions are in, it would adjust properly. 

UI (loses the CSS, but hopefully illustrative):
![image](https://user-images.githubusercontent.com/151620/56839700-a065e380-6838-11e9-9ca9-6aa32755b8a3.png)

In the inspector:
![image](https://user-images.githubusercontent.com/151620/56839741-cab7a100-6838-11e9-9bf9-009f4286e4ef.png)

**Comment by leggett** [comment]
The search box is in the app bar with the menu button, profile button and some stuff I hide. 

The actions, pagination, and settings are all in an action bar that I move on top of the app bar.

Moving elements to different parent divs seems unwise and likely to break things. I don't think I can even move it... I'd have to delete it and recreate it. 

Compatibility with other extensions is on my list but not a priority due to the added complexity. Boomerang is definitely the one I hear the most about though... so if I get to it, it is likely to get supported.
